// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/Zkart.proto

package protobuilder;

/**
 * Protobuf type {@code Zkart.AdminsDB}
 */
public final class AdminsDB extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Zkart.AdminsDB)
    AdminsDBOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AdminsDB.newBuilder() to construct.
  private AdminsDB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AdminsDB() {
    admins_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AdminsDB();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AdminsDB(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              admins_ = new java.util.ArrayList<protobuilder.Admin>();
              mutable_bitField0_ |= 0x00000001;
            }
            admins_.add(
                input.readMessage(protobuilder.Admin.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        admins_ = java.util.Collections.unmodifiableList(admins_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuilder.ZkartProtos.internal_static_Zkart_AdminsDB_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuilder.ZkartProtos.internal_static_Zkart_AdminsDB_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuilder.AdminsDB.class, protobuilder.AdminsDB.Builder.class);
  }

  public static final int ADMINS_FIELD_NUMBER = 1;
  private java.util.List<protobuilder.Admin> admins_;
  /**
   * <code>repeated .Zkart.Admin admins = 1;</code>
   */
  @java.lang.Override
  public java.util.List<protobuilder.Admin> getAdminsList() {
    return admins_;
  }
  /**
   * <code>repeated .Zkart.Admin admins = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends protobuilder.AdminOrBuilder> 
      getAdminsOrBuilderList() {
    return admins_;
  }
  /**
   * <code>repeated .Zkart.Admin admins = 1;</code>
   */
  @java.lang.Override
  public int getAdminsCount() {
    return admins_.size();
  }
  /**
   * <code>repeated .Zkart.Admin admins = 1;</code>
   */
  @java.lang.Override
  public protobuilder.Admin getAdmins(int index) {
    return admins_.get(index);
  }
  /**
   * <code>repeated .Zkart.Admin admins = 1;</code>
   */
  @java.lang.Override
  public protobuilder.AdminOrBuilder getAdminsOrBuilder(
      int index) {
    return admins_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getAdminsCount(); i++) {
      if (!getAdmins(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < admins_.size(); i++) {
      output.writeMessage(1, admins_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < admins_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, admins_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuilder.AdminsDB)) {
      return super.equals(obj);
    }
    protobuilder.AdminsDB other = (protobuilder.AdminsDB) obj;

    if (!getAdminsList()
        .equals(other.getAdminsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAdminsCount() > 0) {
      hash = (37 * hash) + ADMINS_FIELD_NUMBER;
      hash = (53 * hash) + getAdminsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuilder.AdminsDB parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuilder.AdminsDB parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuilder.AdminsDB parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuilder.AdminsDB parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuilder.AdminsDB parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuilder.AdminsDB parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuilder.AdminsDB parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuilder.AdminsDB parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuilder.AdminsDB parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuilder.AdminsDB parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuilder.AdminsDB parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuilder.AdminsDB parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuilder.AdminsDB prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Zkart.AdminsDB}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Zkart.AdminsDB)
      protobuilder.AdminsDBOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuilder.ZkartProtos.internal_static_Zkart_AdminsDB_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuilder.ZkartProtos.internal_static_Zkart_AdminsDB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuilder.AdminsDB.class, protobuilder.AdminsDB.Builder.class);
    }

    // Construct using protobuilder.AdminsDB.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAdminsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (adminsBuilder_ == null) {
        admins_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        adminsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuilder.ZkartProtos.internal_static_Zkart_AdminsDB_descriptor;
    }

    @java.lang.Override
    public protobuilder.AdminsDB getDefaultInstanceForType() {
      return protobuilder.AdminsDB.getDefaultInstance();
    }

    @java.lang.Override
    public protobuilder.AdminsDB build() {
      protobuilder.AdminsDB result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protobuilder.AdminsDB buildPartial() {
      protobuilder.AdminsDB result = new protobuilder.AdminsDB(this);
      int from_bitField0_ = bitField0_;
      if (adminsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          admins_ = java.util.Collections.unmodifiableList(admins_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.admins_ = admins_;
      } else {
        result.admins_ = adminsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuilder.AdminsDB) {
        return mergeFrom((protobuilder.AdminsDB)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuilder.AdminsDB other) {
      if (other == protobuilder.AdminsDB.getDefaultInstance()) return this;
      if (adminsBuilder_ == null) {
        if (!other.admins_.isEmpty()) {
          if (admins_.isEmpty()) {
            admins_ = other.admins_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAdminsIsMutable();
            admins_.addAll(other.admins_);
          }
          onChanged();
        }
      } else {
        if (!other.admins_.isEmpty()) {
          if (adminsBuilder_.isEmpty()) {
            adminsBuilder_.dispose();
            adminsBuilder_ = null;
            admins_ = other.admins_;
            bitField0_ = (bitField0_ & ~0x00000001);
            adminsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAdminsFieldBuilder() : null;
          } else {
            adminsBuilder_.addAllMessages(other.admins_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      for (int i = 0; i < getAdminsCount(); i++) {
        if (!getAdmins(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuilder.AdminsDB parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuilder.AdminsDB) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<protobuilder.Admin> admins_ =
      java.util.Collections.emptyList();
    private void ensureAdminsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        admins_ = new java.util.ArrayList<protobuilder.Admin>(admins_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuilder.Admin, protobuilder.Admin.Builder, protobuilder.AdminOrBuilder> adminsBuilder_;

    /**
     * <code>repeated .Zkart.Admin admins = 1;</code>
     */
    public java.util.List<protobuilder.Admin> getAdminsList() {
      if (adminsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(admins_);
      } else {
        return adminsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Zkart.Admin admins = 1;</code>
     */
    public int getAdminsCount() {
      if (adminsBuilder_ == null) {
        return admins_.size();
      } else {
        return adminsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Zkart.Admin admins = 1;</code>
     */
    public protobuilder.Admin getAdmins(int index) {
      if (adminsBuilder_ == null) {
        return admins_.get(index);
      } else {
        return adminsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Zkart.Admin admins = 1;</code>
     */
    public Builder setAdmins(
        int index, protobuilder.Admin value) {
      if (adminsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAdminsIsMutable();
        admins_.set(index, value);
        onChanged();
      } else {
        adminsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Admin admins = 1;</code>
     */
    public Builder setAdmins(
        int index, protobuilder.Admin.Builder builderForValue) {
      if (adminsBuilder_ == null) {
        ensureAdminsIsMutable();
        admins_.set(index, builderForValue.build());
        onChanged();
      } else {
        adminsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Admin admins = 1;</code>
     */
    public Builder addAdmins(protobuilder.Admin value) {
      if (adminsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAdminsIsMutable();
        admins_.add(value);
        onChanged();
      } else {
        adminsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Admin admins = 1;</code>
     */
    public Builder addAdmins(
        int index, protobuilder.Admin value) {
      if (adminsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAdminsIsMutable();
        admins_.add(index, value);
        onChanged();
      } else {
        adminsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Admin admins = 1;</code>
     */
    public Builder addAdmins(
        protobuilder.Admin.Builder builderForValue) {
      if (adminsBuilder_ == null) {
        ensureAdminsIsMutable();
        admins_.add(builderForValue.build());
        onChanged();
      } else {
        adminsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Admin admins = 1;</code>
     */
    public Builder addAdmins(
        int index, protobuilder.Admin.Builder builderForValue) {
      if (adminsBuilder_ == null) {
        ensureAdminsIsMutable();
        admins_.add(index, builderForValue.build());
        onChanged();
      } else {
        adminsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Admin admins = 1;</code>
     */
    public Builder addAllAdmins(
        java.lang.Iterable<? extends protobuilder.Admin> values) {
      if (adminsBuilder_ == null) {
        ensureAdminsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, admins_);
        onChanged();
      } else {
        adminsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Admin admins = 1;</code>
     */
    public Builder clearAdmins() {
      if (adminsBuilder_ == null) {
        admins_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        adminsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Admin admins = 1;</code>
     */
    public Builder removeAdmins(int index) {
      if (adminsBuilder_ == null) {
        ensureAdminsIsMutable();
        admins_.remove(index);
        onChanged();
      } else {
        adminsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Admin admins = 1;</code>
     */
    public protobuilder.Admin.Builder getAdminsBuilder(
        int index) {
      return getAdminsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Zkart.Admin admins = 1;</code>
     */
    public protobuilder.AdminOrBuilder getAdminsOrBuilder(
        int index) {
      if (adminsBuilder_ == null) {
        return admins_.get(index);  } else {
        return adminsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Zkart.Admin admins = 1;</code>
     */
    public java.util.List<? extends protobuilder.AdminOrBuilder> 
         getAdminsOrBuilderList() {
      if (adminsBuilder_ != null) {
        return adminsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(admins_);
      }
    }
    /**
     * <code>repeated .Zkart.Admin admins = 1;</code>
     */
    public protobuilder.Admin.Builder addAdminsBuilder() {
      return getAdminsFieldBuilder().addBuilder(
          protobuilder.Admin.getDefaultInstance());
    }
    /**
     * <code>repeated .Zkart.Admin admins = 1;</code>
     */
    public protobuilder.Admin.Builder addAdminsBuilder(
        int index) {
      return getAdminsFieldBuilder().addBuilder(
          index, protobuilder.Admin.getDefaultInstance());
    }
    /**
     * <code>repeated .Zkart.Admin admins = 1;</code>
     */
    public java.util.List<protobuilder.Admin.Builder> 
         getAdminsBuilderList() {
      return getAdminsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuilder.Admin, protobuilder.Admin.Builder, protobuilder.AdminOrBuilder> 
        getAdminsFieldBuilder() {
      if (adminsBuilder_ == null) {
        adminsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protobuilder.Admin, protobuilder.Admin.Builder, protobuilder.AdminOrBuilder>(
                admins_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        admins_ = null;
      }
      return adminsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Zkart.AdminsDB)
  }

  // @@protoc_insertion_point(class_scope:Zkart.AdminsDB)
  private static final protobuilder.AdminsDB DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuilder.AdminsDB();
  }

  public static protobuilder.AdminsDB getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<AdminsDB>
      PARSER = new com.google.protobuf.AbstractParser<AdminsDB>() {
    @java.lang.Override
    public AdminsDB parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AdminsDB(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AdminsDB> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AdminsDB> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protobuilder.AdminsDB getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

