// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/Zkart.proto

package protobuilder;

public interface AdminsDBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Zkart.AdminsDB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Zkart.Admin admins = 1;</code>
   */
  java.util.List<protobuilder.Admin> 
      getAdminsList();
  /**
   * <code>repeated .Zkart.Admin admins = 1;</code>
   */
  protobuilder.Admin getAdmins(int index);
  /**
   * <code>repeated .Zkart.Admin admins = 1;</code>
   */
  int getAdminsCount();
  /**
   * <code>repeated .Zkart.Admin admins = 1;</code>
   */
  java.util.List<? extends protobuilder.AdminOrBuilder> 
      getAdminsOrBuilderList();
  /**
   * <code>repeated .Zkart.Admin admins = 1;</code>
   */
  protobuilder.AdminOrBuilder getAdminsOrBuilder(
      int index);
}
