// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/Zkart.proto

package protobuilder;

public interface CartItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Zkart.CartItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 sNo = 1;</code>
   * @return Whether the sNo field is set.
   */
  boolean hasSNo();
  /**
   * <code>required int32 sNo = 1;</code>
   * @return The sNo.
   */
  int getSNo();

  /**
   * <code>required int64 customerID = 2;</code>
   * @return Whether the customerID field is set.
   */
  boolean hasCustomerID();
  /**
   * <code>required int64 customerID = 2;</code>
   * @return The customerID.
   */
  long getCustomerID();

  /**
   * <code>required int64 productID = 3;</code>
   * @return Whether the productID field is set.
   */
  boolean hasProductID();
  /**
   * <code>required int64 productID = 3;</code>
   * @return The productID.
   */
  long getProductID();

  /**
   * <code>required int32 quantity = 4;</code>
   * @return Whether the quantity field is set.
   */
  boolean hasQuantity();
  /**
   * <code>required int32 quantity = 4;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <code>required double productRate = 5;</code>
   * @return Whether the productRate field is set.
   */
  boolean hasProductRate();
  /**
   * <code>required double productRate = 5;</code>
   * @return The productRate.
   */
  double getProductRate();

  /**
   * <code>required double lineTotal = 6;</code>
   * @return Whether the lineTotal field is set.
   */
  boolean hasLineTotal();
  /**
   * <code>required double lineTotal = 6;</code>
   * @return The lineTotal.
   */
  double getLineTotal();
}
