// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/Zkart.proto

package protobuilder;

/**
 * Protobuf type {@code Zkart.CartItem}
 */
public final class CartItem extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Zkart.CartItem)
    CartItemOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CartItem.newBuilder() to construct.
  private CartItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CartItem() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CartItem();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CartItem(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            sNo_ = input.readInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            customerID_ = input.readInt64();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            productID_ = input.readInt64();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            quantity_ = input.readInt32();
            break;
          }
          case 41: {
            bitField0_ |= 0x00000010;
            productRate_ = input.readDouble();
            break;
          }
          case 49: {
            bitField0_ |= 0x00000020;
            lineTotal_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuilder.ZkartProtos.internal_static_Zkart_CartItem_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuilder.ZkartProtos.internal_static_Zkart_CartItem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuilder.CartItem.class, protobuilder.CartItem.Builder.class);
  }

  private int bitField0_;
  public static final int SNO_FIELD_NUMBER = 1;
  private int sNo_;
  /**
   * <code>required int32 sNo = 1;</code>
   * @return Whether the sNo field is set.
   */
  @java.lang.Override
  public boolean hasSNo() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required int32 sNo = 1;</code>
   * @return The sNo.
   */
  @java.lang.Override
  public int getSNo() {
    return sNo_;
  }

  public static final int CUSTOMERID_FIELD_NUMBER = 2;
  private long customerID_;
  /**
   * <code>required int64 customerID = 2;</code>
   * @return Whether the customerID field is set.
   */
  @java.lang.Override
  public boolean hasCustomerID() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required int64 customerID = 2;</code>
   * @return The customerID.
   */
  @java.lang.Override
  public long getCustomerID() {
    return customerID_;
  }

  public static final int PRODUCTID_FIELD_NUMBER = 3;
  private long productID_;
  /**
   * <code>required int64 productID = 3;</code>
   * @return Whether the productID field is set.
   */
  @java.lang.Override
  public boolean hasProductID() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required int64 productID = 3;</code>
   * @return The productID.
   */
  @java.lang.Override
  public long getProductID() {
    return productID_;
  }

  public static final int QUANTITY_FIELD_NUMBER = 4;
  private int quantity_;
  /**
   * <code>required int32 quantity = 4;</code>
   * @return Whether the quantity field is set.
   */
  @java.lang.Override
  public boolean hasQuantity() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>required int32 quantity = 4;</code>
   * @return The quantity.
   */
  @java.lang.Override
  public int getQuantity() {
    return quantity_;
  }

  public static final int PRODUCTRATE_FIELD_NUMBER = 5;
  private double productRate_;
  /**
   * <code>required double productRate = 5;</code>
   * @return Whether the productRate field is set.
   */
  @java.lang.Override
  public boolean hasProductRate() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>required double productRate = 5;</code>
   * @return The productRate.
   */
  @java.lang.Override
  public double getProductRate() {
    return productRate_;
  }

  public static final int LINETOTAL_FIELD_NUMBER = 6;
  private double lineTotal_;
  /**
   * <code>required double lineTotal = 6;</code>
   * @return Whether the lineTotal field is set.
   */
  @java.lang.Override
  public boolean hasLineTotal() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>required double lineTotal = 6;</code>
   * @return The lineTotal.
   */
  @java.lang.Override
  public double getLineTotal() {
    return lineTotal_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasSNo()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasCustomerID()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasProductID()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasQuantity()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasProductRate()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasLineTotal()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, sNo_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(2, customerID_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt64(3, productID_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt32(4, quantity_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeDouble(5, productRate_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeDouble(6, lineTotal_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, sNo_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, customerID_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, productID_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, quantity_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, productRate_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, lineTotal_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuilder.CartItem)) {
      return super.equals(obj);
    }
    protobuilder.CartItem other = (protobuilder.CartItem) obj;

    if (hasSNo() != other.hasSNo()) return false;
    if (hasSNo()) {
      if (getSNo()
          != other.getSNo()) return false;
    }
    if (hasCustomerID() != other.hasCustomerID()) return false;
    if (hasCustomerID()) {
      if (getCustomerID()
          != other.getCustomerID()) return false;
    }
    if (hasProductID() != other.hasProductID()) return false;
    if (hasProductID()) {
      if (getProductID()
          != other.getProductID()) return false;
    }
    if (hasQuantity() != other.hasQuantity()) return false;
    if (hasQuantity()) {
      if (getQuantity()
          != other.getQuantity()) return false;
    }
    if (hasProductRate() != other.hasProductRate()) return false;
    if (hasProductRate()) {
      if (java.lang.Double.doubleToLongBits(getProductRate())
          != java.lang.Double.doubleToLongBits(
              other.getProductRate())) return false;
    }
    if (hasLineTotal() != other.hasLineTotal()) return false;
    if (hasLineTotal()) {
      if (java.lang.Double.doubleToLongBits(getLineTotal())
          != java.lang.Double.doubleToLongBits(
              other.getLineTotal())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSNo()) {
      hash = (37 * hash) + SNO_FIELD_NUMBER;
      hash = (53 * hash) + getSNo();
    }
    if (hasCustomerID()) {
      hash = (37 * hash) + CUSTOMERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCustomerID());
    }
    if (hasProductID()) {
      hash = (37 * hash) + PRODUCTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProductID());
    }
    if (hasQuantity()) {
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity();
    }
    if (hasProductRate()) {
      hash = (37 * hash) + PRODUCTRATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getProductRate()));
    }
    if (hasLineTotal()) {
      hash = (37 * hash) + LINETOTAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLineTotal()));
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuilder.CartItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuilder.CartItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuilder.CartItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuilder.CartItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuilder.CartItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuilder.CartItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuilder.CartItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuilder.CartItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuilder.CartItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuilder.CartItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuilder.CartItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuilder.CartItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuilder.CartItem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Zkart.CartItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Zkart.CartItem)
      protobuilder.CartItemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuilder.ZkartProtos.internal_static_Zkart_CartItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuilder.ZkartProtos.internal_static_Zkart_CartItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuilder.CartItem.class, protobuilder.CartItem.Builder.class);
    }

    // Construct using protobuilder.CartItem.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      sNo_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      customerID_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      productID_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      quantity_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      productRate_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000010);
      lineTotal_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuilder.ZkartProtos.internal_static_Zkart_CartItem_descriptor;
    }

    @java.lang.Override
    public protobuilder.CartItem getDefaultInstanceForType() {
      return protobuilder.CartItem.getDefaultInstance();
    }

    @java.lang.Override
    public protobuilder.CartItem build() {
      protobuilder.CartItem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protobuilder.CartItem buildPartial() {
      protobuilder.CartItem result = new protobuilder.CartItem(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sNo_ = sNo_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.customerID_ = customerID_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.productID_ = productID_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.quantity_ = quantity_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.productRate_ = productRate_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.lineTotal_ = lineTotal_;
        to_bitField0_ |= 0x00000020;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuilder.CartItem) {
        return mergeFrom((protobuilder.CartItem)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuilder.CartItem other) {
      if (other == protobuilder.CartItem.getDefaultInstance()) return this;
      if (other.hasSNo()) {
        setSNo(other.getSNo());
      }
      if (other.hasCustomerID()) {
        setCustomerID(other.getCustomerID());
      }
      if (other.hasProductID()) {
        setProductID(other.getProductID());
      }
      if (other.hasQuantity()) {
        setQuantity(other.getQuantity());
      }
      if (other.hasProductRate()) {
        setProductRate(other.getProductRate());
      }
      if (other.hasLineTotal()) {
        setLineTotal(other.getLineTotal());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasSNo()) {
        return false;
      }
      if (!hasCustomerID()) {
        return false;
      }
      if (!hasProductID()) {
        return false;
      }
      if (!hasQuantity()) {
        return false;
      }
      if (!hasProductRate()) {
        return false;
      }
      if (!hasLineTotal()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuilder.CartItem parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuilder.CartItem) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int sNo_ ;
    /**
     * <code>required int32 sNo = 1;</code>
     * @return Whether the sNo field is set.
     */
    @java.lang.Override
    public boolean hasSNo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 sNo = 1;</code>
     * @return The sNo.
     */
    @java.lang.Override
    public int getSNo() {
      return sNo_;
    }
    /**
     * <code>required int32 sNo = 1;</code>
     * @param value The sNo to set.
     * @return This builder for chaining.
     */
    public Builder setSNo(int value) {
      bitField0_ |= 0x00000001;
      sNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 sNo = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSNo() {
      bitField0_ = (bitField0_ & ~0x00000001);
      sNo_ = 0;
      onChanged();
      return this;
    }

    private long customerID_ ;
    /**
     * <code>required int64 customerID = 2;</code>
     * @return Whether the customerID field is set.
     */
    @java.lang.Override
    public boolean hasCustomerID() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int64 customerID = 2;</code>
     * @return The customerID.
     */
    @java.lang.Override
    public long getCustomerID() {
      return customerID_;
    }
    /**
     * <code>required int64 customerID = 2;</code>
     * @param value The customerID to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerID(long value) {
      bitField0_ |= 0x00000002;
      customerID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 customerID = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCustomerID() {
      bitField0_ = (bitField0_ & ~0x00000002);
      customerID_ = 0L;
      onChanged();
      return this;
    }

    private long productID_ ;
    /**
     * <code>required int64 productID = 3;</code>
     * @return Whether the productID field is set.
     */
    @java.lang.Override
    public boolean hasProductID() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int64 productID = 3;</code>
     * @return The productID.
     */
    @java.lang.Override
    public long getProductID() {
      return productID_;
    }
    /**
     * <code>required int64 productID = 3;</code>
     * @param value The productID to set.
     * @return This builder for chaining.
     */
    public Builder setProductID(long value) {
      bitField0_ |= 0x00000004;
      productID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 productID = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductID() {
      bitField0_ = (bitField0_ & ~0x00000004);
      productID_ = 0L;
      onChanged();
      return this;
    }

    private int quantity_ ;
    /**
     * <code>required int32 quantity = 4;</code>
     * @return Whether the quantity field is set.
     */
    @java.lang.Override
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required int32 quantity = 4;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public int getQuantity() {
      return quantity_;
    }
    /**
     * <code>required int32 quantity = 4;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(int value) {
      bitField0_ |= 0x00000008;
      quantity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 quantity = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      bitField0_ = (bitField0_ & ~0x00000008);
      quantity_ = 0;
      onChanged();
      return this;
    }

    private double productRate_ ;
    /**
     * <code>required double productRate = 5;</code>
     * @return Whether the productRate field is set.
     */
    @java.lang.Override
    public boolean hasProductRate() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required double productRate = 5;</code>
     * @return The productRate.
     */
    @java.lang.Override
    public double getProductRate() {
      return productRate_;
    }
    /**
     * <code>required double productRate = 5;</code>
     * @param value The productRate to set.
     * @return This builder for chaining.
     */
    public Builder setProductRate(double value) {
      bitField0_ |= 0x00000010;
      productRate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required double productRate = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductRate() {
      bitField0_ = (bitField0_ & ~0x00000010);
      productRate_ = 0D;
      onChanged();
      return this;
    }

    private double lineTotal_ ;
    /**
     * <code>required double lineTotal = 6;</code>
     * @return Whether the lineTotal field is set.
     */
    @java.lang.Override
    public boolean hasLineTotal() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required double lineTotal = 6;</code>
     * @return The lineTotal.
     */
    @java.lang.Override
    public double getLineTotal() {
      return lineTotal_;
    }
    /**
     * <code>required double lineTotal = 6;</code>
     * @param value The lineTotal to set.
     * @return This builder for chaining.
     */
    public Builder setLineTotal(double value) {
      bitField0_ |= 0x00000020;
      lineTotal_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required double lineTotal = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLineTotal() {
      bitField0_ = (bitField0_ & ~0x00000020);
      lineTotal_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Zkart.CartItem)
  }

  // @@protoc_insertion_point(class_scope:Zkart.CartItem)
  private static final protobuilder.CartItem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuilder.CartItem();
  }

  public static protobuilder.CartItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<CartItem>
      PARSER = new com.google.protobuf.AbstractParser<CartItem>() {
    @java.lang.Override
    public CartItem parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CartItem(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CartItem> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CartItem> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protobuilder.CartItem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

