// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/Zkart.proto

package protobuilder;

public interface CustomerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Zkart.Customer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>required int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>required string name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>required string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>required string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>required string email = 3;</code>
   * @return Whether the email field is set.
   */
  boolean hasEmail();
  /**
   * <code>required string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>required string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>required string password = 4;</code>
   * @return Whether the password field is set.
   */
  boolean hasPassword();
  /**
   * <code>required string password = 4;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>required string password = 4;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>optional int64 phoneNumber = 5;</code>
   * @return Whether the phoneNumber field is set.
   */
  boolean hasPhoneNumber();
  /**
   * <code>optional int64 phoneNumber = 5;</code>
   * @return The phoneNumber.
   */
  long getPhoneNumber();

  /**
   * <code>repeated .Zkart.Deal deals = 6;</code>
   */
  java.util.List<protobuilder.Deal> 
      getDealsList();
  /**
   * <code>repeated .Zkart.Deal deals = 6;</code>
   */
  protobuilder.Deal getDeals(int index);
  /**
   * <code>repeated .Zkart.Deal deals = 6;</code>
   */
  int getDealsCount();
  /**
   * <code>repeated .Zkart.Deal deals = 6;</code>
   */
  java.util.List<? extends protobuilder.DealOrBuilder> 
      getDealsOrBuilderList();
  /**
   * <code>repeated .Zkart.Deal deals = 6;</code>
   */
  protobuilder.DealOrBuilder getDealsOrBuilder(
      int index);

  /**
   * <code>repeated .Zkart.CartItem cartItems = 7;</code>
   */
  java.util.List<protobuilder.CartItem> 
      getCartItemsList();
  /**
   * <code>repeated .Zkart.CartItem cartItems = 7;</code>
   */
  protobuilder.CartItem getCartItems(int index);
  /**
   * <code>repeated .Zkart.CartItem cartItems = 7;</code>
   */
  int getCartItemsCount();
  /**
   * <code>repeated .Zkart.CartItem cartItems = 7;</code>
   */
  java.util.List<? extends protobuilder.CartItemOrBuilder> 
      getCartItemsOrBuilderList();
  /**
   * <code>repeated .Zkart.CartItem cartItems = 7;</code>
   */
  protobuilder.CartItemOrBuilder getCartItemsOrBuilder(
      int index);

  /**
   * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
   */
  java.util.List<protobuilder.Invoice> 
      getOrderHistoryList();
  /**
   * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
   */
  protobuilder.Invoice getOrderHistory(int index);
  /**
   * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
   */
  int getOrderHistoryCount();
  /**
   * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
   */
  java.util.List<? extends protobuilder.InvoiceOrBuilder> 
      getOrderHistoryOrBuilderList();
  /**
   * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
   */
  protobuilder.InvoiceOrBuilder getOrderHistoryOrBuilder(
      int index);
}
