// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/Zkart.proto

package protobuilder;

/**
 * Protobuf type {@code Zkart.Customer}
 */
public final class Customer extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Zkart.Customer)
    CustomerOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Customer.newBuilder() to construct.
  private Customer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Customer() {
    name_ = "";
    email_ = "";
    password_ = "";
    deals_ = java.util.Collections.emptyList();
    cartItems_ = java.util.Collections.emptyList();
    orderHistory_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Customer();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Customer(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            id_ = input.readInt64();
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            name_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            email_ = bs;
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            password_ = bs;
            break;
          }
          case 40: {
            bitField0_ |= 0x00000010;
            phoneNumber_ = input.readInt64();
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) != 0)) {
              deals_ = new java.util.ArrayList<protobuilder.Deal>();
              mutable_bitField0_ |= 0x00000020;
            }
            deals_.add(
                input.readMessage(protobuilder.Deal.PARSER, extensionRegistry));
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000040) != 0)) {
              cartItems_ = new java.util.ArrayList<protobuilder.CartItem>();
              mutable_bitField0_ |= 0x00000040;
            }
            cartItems_.add(
                input.readMessage(protobuilder.CartItem.PARSER, extensionRegistry));
            break;
          }
          case 66: {
            if (!((mutable_bitField0_ & 0x00000080) != 0)) {
              orderHistory_ = new java.util.ArrayList<protobuilder.Invoice>();
              mutable_bitField0_ |= 0x00000080;
            }
            orderHistory_.add(
                input.readMessage(protobuilder.Invoice.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000020) != 0)) {
        deals_ = java.util.Collections.unmodifiableList(deals_);
      }
      if (((mutable_bitField0_ & 0x00000040) != 0)) {
        cartItems_ = java.util.Collections.unmodifiableList(cartItems_);
      }
      if (((mutable_bitField0_ & 0x00000080) != 0)) {
        orderHistory_ = java.util.Collections.unmodifiableList(orderHistory_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuilder.ZkartProtos.internal_static_Zkart_Customer_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuilder.ZkartProtos.internal_static_Zkart_Customer_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuilder.Customer.class, protobuilder.Customer.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>required int64 id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>required string name = 2;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_FIELD_NUMBER = 3;
  private volatile java.lang.Object email_;
  /**
   * <code>required string email = 3;</code>
   * @return Whether the email field is set.
   */
  @java.lang.Override
  public boolean hasEmail() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required string email = 3;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        email_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string email = 3;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 4;
  private volatile java.lang.Object password_;
  /**
   * <code>required string password = 4;</code>
   * @return Whether the password field is set.
   */
  @java.lang.Override
  public boolean hasPassword() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>required string password = 4;</code>
   * @return The password.
   */
  @java.lang.Override
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        password_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string password = 4;</code>
   * @return The bytes for password.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONENUMBER_FIELD_NUMBER = 5;
  private long phoneNumber_;
  /**
   * <code>optional int64 phoneNumber = 5;</code>
   * @return Whether the phoneNumber field is set.
   */
  @java.lang.Override
  public boolean hasPhoneNumber() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional int64 phoneNumber = 5;</code>
   * @return The phoneNumber.
   */
  @java.lang.Override
  public long getPhoneNumber() {
    return phoneNumber_;
  }

  public static final int DEALS_FIELD_NUMBER = 6;
  private java.util.List<protobuilder.Deal> deals_;
  /**
   * <code>repeated .Zkart.Deal deals = 6;</code>
   */
  @java.lang.Override
  public java.util.List<protobuilder.Deal> getDealsList() {
    return deals_;
  }
  /**
   * <code>repeated .Zkart.Deal deals = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends protobuilder.DealOrBuilder> 
      getDealsOrBuilderList() {
    return deals_;
  }
  /**
   * <code>repeated .Zkart.Deal deals = 6;</code>
   */
  @java.lang.Override
  public int getDealsCount() {
    return deals_.size();
  }
  /**
   * <code>repeated .Zkart.Deal deals = 6;</code>
   */
  @java.lang.Override
  public protobuilder.Deal getDeals(int index) {
    return deals_.get(index);
  }
  /**
   * <code>repeated .Zkart.Deal deals = 6;</code>
   */
  @java.lang.Override
  public protobuilder.DealOrBuilder getDealsOrBuilder(
      int index) {
    return deals_.get(index);
  }

  public static final int CARTITEMS_FIELD_NUMBER = 7;
  private java.util.List<protobuilder.CartItem> cartItems_;
  /**
   * <code>repeated .Zkart.CartItem cartItems = 7;</code>
   */
  @java.lang.Override
  public java.util.List<protobuilder.CartItem> getCartItemsList() {
    return cartItems_;
  }
  /**
   * <code>repeated .Zkart.CartItem cartItems = 7;</code>
   */
  @java.lang.Override
  public java.util.List<? extends protobuilder.CartItemOrBuilder> 
      getCartItemsOrBuilderList() {
    return cartItems_;
  }
  /**
   * <code>repeated .Zkart.CartItem cartItems = 7;</code>
   */
  @java.lang.Override
  public int getCartItemsCount() {
    return cartItems_.size();
  }
  /**
   * <code>repeated .Zkart.CartItem cartItems = 7;</code>
   */
  @java.lang.Override
  public protobuilder.CartItem getCartItems(int index) {
    return cartItems_.get(index);
  }
  /**
   * <code>repeated .Zkart.CartItem cartItems = 7;</code>
   */
  @java.lang.Override
  public protobuilder.CartItemOrBuilder getCartItemsOrBuilder(
      int index) {
    return cartItems_.get(index);
  }

  public static final int ORDERHISTORY_FIELD_NUMBER = 8;
  private java.util.List<protobuilder.Invoice> orderHistory_;
  /**
   * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
   */
  @java.lang.Override
  public java.util.List<protobuilder.Invoice> getOrderHistoryList() {
    return orderHistory_;
  }
  /**
   * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
   */
  @java.lang.Override
  public java.util.List<? extends protobuilder.InvoiceOrBuilder> 
      getOrderHistoryOrBuilderList() {
    return orderHistory_;
  }
  /**
   * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
   */
  @java.lang.Override
  public int getOrderHistoryCount() {
    return orderHistory_.size();
  }
  /**
   * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
   */
  @java.lang.Override
  public protobuilder.Invoice getOrderHistory(int index) {
    return orderHistory_.get(index);
  }
  /**
   * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
   */
  @java.lang.Override
  public protobuilder.InvoiceOrBuilder getOrderHistoryOrBuilder(
      int index) {
    return orderHistory_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasEmail()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasPassword()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getDealsCount(); i++) {
      if (!getDeals(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    for (int i = 0; i < getCartItemsCount(); i++) {
      if (!getCartItems(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    for (int i = 0; i < getOrderHistoryCount(); i++) {
      if (!getOrderHistory(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt64(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, password_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt64(5, phoneNumber_);
    }
    for (int i = 0; i < deals_.size(); i++) {
      output.writeMessage(6, deals_.get(i));
    }
    for (int i = 0; i < cartItems_.size(); i++) {
      output.writeMessage(7, cartItems_.get(i));
    }
    for (int i = 0; i < orderHistory_.size(); i++) {
      output.writeMessage(8, orderHistory_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, password_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, phoneNumber_);
    }
    for (int i = 0; i < deals_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, deals_.get(i));
    }
    for (int i = 0; i < cartItems_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, cartItems_.get(i));
    }
    for (int i = 0; i < orderHistory_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, orderHistory_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuilder.Customer)) {
      return super.equals(obj);
    }
    protobuilder.Customer other = (protobuilder.Customer) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (getId()
          != other.getId()) return false;
    }
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasEmail() != other.hasEmail()) return false;
    if (hasEmail()) {
      if (!getEmail()
          .equals(other.getEmail())) return false;
    }
    if (hasPassword() != other.hasPassword()) return false;
    if (hasPassword()) {
      if (!getPassword()
          .equals(other.getPassword())) return false;
    }
    if (hasPhoneNumber() != other.hasPhoneNumber()) return false;
    if (hasPhoneNumber()) {
      if (getPhoneNumber()
          != other.getPhoneNumber()) return false;
    }
    if (!getDealsList()
        .equals(other.getDealsList())) return false;
    if (!getCartItemsList()
        .equals(other.getCartItemsList())) return false;
    if (!getOrderHistoryList()
        .equals(other.getOrderHistoryList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasEmail()) {
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
    }
    if (hasPassword()) {
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
    }
    if (hasPhoneNumber()) {
      hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPhoneNumber());
    }
    if (getDealsCount() > 0) {
      hash = (37 * hash) + DEALS_FIELD_NUMBER;
      hash = (53 * hash) + getDealsList().hashCode();
    }
    if (getCartItemsCount() > 0) {
      hash = (37 * hash) + CARTITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getCartItemsList().hashCode();
    }
    if (getOrderHistoryCount() > 0) {
      hash = (37 * hash) + ORDERHISTORY_FIELD_NUMBER;
      hash = (53 * hash) + getOrderHistoryList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuilder.Customer parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuilder.Customer parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuilder.Customer parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuilder.Customer parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuilder.Customer parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuilder.Customer parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuilder.Customer parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuilder.Customer parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuilder.Customer parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuilder.Customer parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuilder.Customer parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuilder.Customer parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuilder.Customer prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Zkart.Customer}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Zkart.Customer)
      protobuilder.CustomerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuilder.ZkartProtos.internal_static_Zkart_Customer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuilder.ZkartProtos.internal_static_Zkart_Customer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuilder.Customer.class, protobuilder.Customer.Builder.class);
    }

    // Construct using protobuilder.Customer.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDealsFieldBuilder();
        getCartItemsFieldBuilder();
        getOrderHistoryFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      email_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      password_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      phoneNumber_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000010);
      if (dealsBuilder_ == null) {
        deals_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        dealsBuilder_.clear();
      }
      if (cartItemsBuilder_ == null) {
        cartItems_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
      } else {
        cartItemsBuilder_.clear();
      }
      if (orderHistoryBuilder_ == null) {
        orderHistory_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
      } else {
        orderHistoryBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuilder.ZkartProtos.internal_static_Zkart_Customer_descriptor;
    }

    @java.lang.Override
    public protobuilder.Customer getDefaultInstanceForType() {
      return protobuilder.Customer.getDefaultInstance();
    }

    @java.lang.Override
    public protobuilder.Customer build() {
      protobuilder.Customer result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protobuilder.Customer buildPartial() {
      protobuilder.Customer result = new protobuilder.Customer(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.email_ = email_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.password_ = password_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.phoneNumber_ = phoneNumber_;
        to_bitField0_ |= 0x00000010;
      }
      if (dealsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          deals_ = java.util.Collections.unmodifiableList(deals_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.deals_ = deals_;
      } else {
        result.deals_ = dealsBuilder_.build();
      }
      if (cartItemsBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0)) {
          cartItems_ = java.util.Collections.unmodifiableList(cartItems_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.cartItems_ = cartItems_;
      } else {
        result.cartItems_ = cartItemsBuilder_.build();
      }
      if (orderHistoryBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0)) {
          orderHistory_ = java.util.Collections.unmodifiableList(orderHistory_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.orderHistory_ = orderHistory_;
      } else {
        result.orderHistory_ = orderHistoryBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuilder.Customer) {
        return mergeFrom((protobuilder.Customer)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuilder.Customer other) {
      if (other == protobuilder.Customer.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000002;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasEmail()) {
        bitField0_ |= 0x00000004;
        email_ = other.email_;
        onChanged();
      }
      if (other.hasPassword()) {
        bitField0_ |= 0x00000008;
        password_ = other.password_;
        onChanged();
      }
      if (other.hasPhoneNumber()) {
        setPhoneNumber(other.getPhoneNumber());
      }
      if (dealsBuilder_ == null) {
        if (!other.deals_.isEmpty()) {
          if (deals_.isEmpty()) {
            deals_ = other.deals_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureDealsIsMutable();
            deals_.addAll(other.deals_);
          }
          onChanged();
        }
      } else {
        if (!other.deals_.isEmpty()) {
          if (dealsBuilder_.isEmpty()) {
            dealsBuilder_.dispose();
            dealsBuilder_ = null;
            deals_ = other.deals_;
            bitField0_ = (bitField0_ & ~0x00000020);
            dealsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDealsFieldBuilder() : null;
          } else {
            dealsBuilder_.addAllMessages(other.deals_);
          }
        }
      }
      if (cartItemsBuilder_ == null) {
        if (!other.cartItems_.isEmpty()) {
          if (cartItems_.isEmpty()) {
            cartItems_ = other.cartItems_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureCartItemsIsMutable();
            cartItems_.addAll(other.cartItems_);
          }
          onChanged();
        }
      } else {
        if (!other.cartItems_.isEmpty()) {
          if (cartItemsBuilder_.isEmpty()) {
            cartItemsBuilder_.dispose();
            cartItemsBuilder_ = null;
            cartItems_ = other.cartItems_;
            bitField0_ = (bitField0_ & ~0x00000040);
            cartItemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCartItemsFieldBuilder() : null;
          } else {
            cartItemsBuilder_.addAllMessages(other.cartItems_);
          }
        }
      }
      if (orderHistoryBuilder_ == null) {
        if (!other.orderHistory_.isEmpty()) {
          if (orderHistory_.isEmpty()) {
            orderHistory_ = other.orderHistory_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureOrderHistoryIsMutable();
            orderHistory_.addAll(other.orderHistory_);
          }
          onChanged();
        }
      } else {
        if (!other.orderHistory_.isEmpty()) {
          if (orderHistoryBuilder_.isEmpty()) {
            orderHistoryBuilder_.dispose();
            orderHistoryBuilder_ = null;
            orderHistory_ = other.orderHistory_;
            bitField0_ = (bitField0_ & ~0x00000080);
            orderHistoryBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOrderHistoryFieldBuilder() : null;
          } else {
            orderHistoryBuilder_.addAllMessages(other.orderHistory_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasId()) {
        return false;
      }
      if (!hasName()) {
        return false;
      }
      if (!hasEmail()) {
        return false;
      }
      if (!hasPassword()) {
        return false;
      }
      for (int i = 0; i < getDealsCount(); i++) {
        if (!getDeals(i).isInitialized()) {
          return false;
        }
      }
      for (int i = 0; i < getCartItemsCount(); i++) {
        if (!getCartItems(i).isInitialized()) {
          return false;
        }
      }
      for (int i = 0; i < getOrderHistoryCount(); i++) {
        if (!getOrderHistory(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuilder.Customer parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuilder.Customer) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>required int64 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>required int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>required string name = 2;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>required string email = 3;</code>
     * @return Whether the email field is set.
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string email = 3;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string email = 3;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string email = 3;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string email = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      bitField0_ = (bitField0_ & ~0x00000004);
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <code>required string email = 3;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      email_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object password_ = "";
    /**
     * <code>required string password = 4;</code>
     * @return Whether the password field is set.
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string password = 4;</code>
     * @return The password.
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string password = 4;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string password = 4;</code>
     * @param value The password to set.
     * @return This builder for chaining.
     */
    public Builder setPassword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      password_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string password = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassword() {
      bitField0_ = (bitField0_ & ~0x00000008);
      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    /**
     * <code>required string password = 4;</code>
     * @param value The bytes for password to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      password_ = value;
      onChanged();
      return this;
    }

    private long phoneNumber_ ;
    /**
     * <code>optional int64 phoneNumber = 5;</code>
     * @return Whether the phoneNumber field is set.
     */
    @java.lang.Override
    public boolean hasPhoneNumber() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int64 phoneNumber = 5;</code>
     * @return The phoneNumber.
     */
    @java.lang.Override
    public long getPhoneNumber() {
      return phoneNumber_;
    }
    /**
     * <code>optional int64 phoneNumber = 5;</code>
     * @param value The phoneNumber to set.
     * @return This builder for chaining.
     */
    public Builder setPhoneNumber(long value) {
      bitField0_ |= 0x00000010;
      phoneNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 phoneNumber = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhoneNumber() {
      bitField0_ = (bitField0_ & ~0x00000010);
      phoneNumber_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<protobuilder.Deal> deals_ =
      java.util.Collections.emptyList();
    private void ensureDealsIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        deals_ = new java.util.ArrayList<protobuilder.Deal>(deals_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuilder.Deal, protobuilder.Deal.Builder, protobuilder.DealOrBuilder> dealsBuilder_;

    /**
     * <code>repeated .Zkart.Deal deals = 6;</code>
     */
    public java.util.List<protobuilder.Deal> getDealsList() {
      if (dealsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(deals_);
      } else {
        return dealsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Zkart.Deal deals = 6;</code>
     */
    public int getDealsCount() {
      if (dealsBuilder_ == null) {
        return deals_.size();
      } else {
        return dealsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Zkart.Deal deals = 6;</code>
     */
    public protobuilder.Deal getDeals(int index) {
      if (dealsBuilder_ == null) {
        return deals_.get(index);
      } else {
        return dealsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Zkart.Deal deals = 6;</code>
     */
    public Builder setDeals(
        int index, protobuilder.Deal value) {
      if (dealsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDealsIsMutable();
        deals_.set(index, value);
        onChanged();
      } else {
        dealsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Deal deals = 6;</code>
     */
    public Builder setDeals(
        int index, protobuilder.Deal.Builder builderForValue) {
      if (dealsBuilder_ == null) {
        ensureDealsIsMutable();
        deals_.set(index, builderForValue.build());
        onChanged();
      } else {
        dealsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Deal deals = 6;</code>
     */
    public Builder addDeals(protobuilder.Deal value) {
      if (dealsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDealsIsMutable();
        deals_.add(value);
        onChanged();
      } else {
        dealsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Deal deals = 6;</code>
     */
    public Builder addDeals(
        int index, protobuilder.Deal value) {
      if (dealsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDealsIsMutable();
        deals_.add(index, value);
        onChanged();
      } else {
        dealsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Deal deals = 6;</code>
     */
    public Builder addDeals(
        protobuilder.Deal.Builder builderForValue) {
      if (dealsBuilder_ == null) {
        ensureDealsIsMutable();
        deals_.add(builderForValue.build());
        onChanged();
      } else {
        dealsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Deal deals = 6;</code>
     */
    public Builder addDeals(
        int index, protobuilder.Deal.Builder builderForValue) {
      if (dealsBuilder_ == null) {
        ensureDealsIsMutable();
        deals_.add(index, builderForValue.build());
        onChanged();
      } else {
        dealsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Deal deals = 6;</code>
     */
    public Builder addAllDeals(
        java.lang.Iterable<? extends protobuilder.Deal> values) {
      if (dealsBuilder_ == null) {
        ensureDealsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, deals_);
        onChanged();
      } else {
        dealsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Deal deals = 6;</code>
     */
    public Builder clearDeals() {
      if (dealsBuilder_ == null) {
        deals_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        dealsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Deal deals = 6;</code>
     */
    public Builder removeDeals(int index) {
      if (dealsBuilder_ == null) {
        ensureDealsIsMutable();
        deals_.remove(index);
        onChanged();
      } else {
        dealsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Deal deals = 6;</code>
     */
    public protobuilder.Deal.Builder getDealsBuilder(
        int index) {
      return getDealsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Zkart.Deal deals = 6;</code>
     */
    public protobuilder.DealOrBuilder getDealsOrBuilder(
        int index) {
      if (dealsBuilder_ == null) {
        return deals_.get(index);  } else {
        return dealsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Zkart.Deal deals = 6;</code>
     */
    public java.util.List<? extends protobuilder.DealOrBuilder> 
         getDealsOrBuilderList() {
      if (dealsBuilder_ != null) {
        return dealsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(deals_);
      }
    }
    /**
     * <code>repeated .Zkart.Deal deals = 6;</code>
     */
    public protobuilder.Deal.Builder addDealsBuilder() {
      return getDealsFieldBuilder().addBuilder(
          protobuilder.Deal.getDefaultInstance());
    }
    /**
     * <code>repeated .Zkart.Deal deals = 6;</code>
     */
    public protobuilder.Deal.Builder addDealsBuilder(
        int index) {
      return getDealsFieldBuilder().addBuilder(
          index, protobuilder.Deal.getDefaultInstance());
    }
    /**
     * <code>repeated .Zkart.Deal deals = 6;</code>
     */
    public java.util.List<protobuilder.Deal.Builder> 
         getDealsBuilderList() {
      return getDealsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuilder.Deal, protobuilder.Deal.Builder, protobuilder.DealOrBuilder> 
        getDealsFieldBuilder() {
      if (dealsBuilder_ == null) {
        dealsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protobuilder.Deal, protobuilder.Deal.Builder, protobuilder.DealOrBuilder>(
                deals_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        deals_ = null;
      }
      return dealsBuilder_;
    }

    private java.util.List<protobuilder.CartItem> cartItems_ =
      java.util.Collections.emptyList();
    private void ensureCartItemsIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        cartItems_ = new java.util.ArrayList<protobuilder.CartItem>(cartItems_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuilder.CartItem, protobuilder.CartItem.Builder, protobuilder.CartItemOrBuilder> cartItemsBuilder_;

    /**
     * <code>repeated .Zkart.CartItem cartItems = 7;</code>
     */
    public java.util.List<protobuilder.CartItem> getCartItemsList() {
      if (cartItemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(cartItems_);
      } else {
        return cartItemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Zkart.CartItem cartItems = 7;</code>
     */
    public int getCartItemsCount() {
      if (cartItemsBuilder_ == null) {
        return cartItems_.size();
      } else {
        return cartItemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Zkart.CartItem cartItems = 7;</code>
     */
    public protobuilder.CartItem getCartItems(int index) {
      if (cartItemsBuilder_ == null) {
        return cartItems_.get(index);
      } else {
        return cartItemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Zkart.CartItem cartItems = 7;</code>
     */
    public Builder setCartItems(
        int index, protobuilder.CartItem value) {
      if (cartItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCartItemsIsMutable();
        cartItems_.set(index, value);
        onChanged();
      } else {
        cartItemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.CartItem cartItems = 7;</code>
     */
    public Builder setCartItems(
        int index, protobuilder.CartItem.Builder builderForValue) {
      if (cartItemsBuilder_ == null) {
        ensureCartItemsIsMutable();
        cartItems_.set(index, builderForValue.build());
        onChanged();
      } else {
        cartItemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.CartItem cartItems = 7;</code>
     */
    public Builder addCartItems(protobuilder.CartItem value) {
      if (cartItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCartItemsIsMutable();
        cartItems_.add(value);
        onChanged();
      } else {
        cartItemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.CartItem cartItems = 7;</code>
     */
    public Builder addCartItems(
        int index, protobuilder.CartItem value) {
      if (cartItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCartItemsIsMutable();
        cartItems_.add(index, value);
        onChanged();
      } else {
        cartItemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.CartItem cartItems = 7;</code>
     */
    public Builder addCartItems(
        protobuilder.CartItem.Builder builderForValue) {
      if (cartItemsBuilder_ == null) {
        ensureCartItemsIsMutable();
        cartItems_.add(builderForValue.build());
        onChanged();
      } else {
        cartItemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.CartItem cartItems = 7;</code>
     */
    public Builder addCartItems(
        int index, protobuilder.CartItem.Builder builderForValue) {
      if (cartItemsBuilder_ == null) {
        ensureCartItemsIsMutable();
        cartItems_.add(index, builderForValue.build());
        onChanged();
      } else {
        cartItemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.CartItem cartItems = 7;</code>
     */
    public Builder addAllCartItems(
        java.lang.Iterable<? extends protobuilder.CartItem> values) {
      if (cartItemsBuilder_ == null) {
        ensureCartItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cartItems_);
        onChanged();
      } else {
        cartItemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.CartItem cartItems = 7;</code>
     */
    public Builder clearCartItems() {
      if (cartItemsBuilder_ == null) {
        cartItems_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        cartItemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.CartItem cartItems = 7;</code>
     */
    public Builder removeCartItems(int index) {
      if (cartItemsBuilder_ == null) {
        ensureCartItemsIsMutable();
        cartItems_.remove(index);
        onChanged();
      } else {
        cartItemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.CartItem cartItems = 7;</code>
     */
    public protobuilder.CartItem.Builder getCartItemsBuilder(
        int index) {
      return getCartItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Zkart.CartItem cartItems = 7;</code>
     */
    public protobuilder.CartItemOrBuilder getCartItemsOrBuilder(
        int index) {
      if (cartItemsBuilder_ == null) {
        return cartItems_.get(index);  } else {
        return cartItemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Zkart.CartItem cartItems = 7;</code>
     */
    public java.util.List<? extends protobuilder.CartItemOrBuilder> 
         getCartItemsOrBuilderList() {
      if (cartItemsBuilder_ != null) {
        return cartItemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(cartItems_);
      }
    }
    /**
     * <code>repeated .Zkart.CartItem cartItems = 7;</code>
     */
    public protobuilder.CartItem.Builder addCartItemsBuilder() {
      return getCartItemsFieldBuilder().addBuilder(
          protobuilder.CartItem.getDefaultInstance());
    }
    /**
     * <code>repeated .Zkart.CartItem cartItems = 7;</code>
     */
    public protobuilder.CartItem.Builder addCartItemsBuilder(
        int index) {
      return getCartItemsFieldBuilder().addBuilder(
          index, protobuilder.CartItem.getDefaultInstance());
    }
    /**
     * <code>repeated .Zkart.CartItem cartItems = 7;</code>
     */
    public java.util.List<protobuilder.CartItem.Builder> 
         getCartItemsBuilderList() {
      return getCartItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuilder.CartItem, protobuilder.CartItem.Builder, protobuilder.CartItemOrBuilder> 
        getCartItemsFieldBuilder() {
      if (cartItemsBuilder_ == null) {
        cartItemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protobuilder.CartItem, protobuilder.CartItem.Builder, protobuilder.CartItemOrBuilder>(
                cartItems_,
                ((bitField0_ & 0x00000040) != 0),
                getParentForChildren(),
                isClean());
        cartItems_ = null;
      }
      return cartItemsBuilder_;
    }

    private java.util.List<protobuilder.Invoice> orderHistory_ =
      java.util.Collections.emptyList();
    private void ensureOrderHistoryIsMutable() {
      if (!((bitField0_ & 0x00000080) != 0)) {
        orderHistory_ = new java.util.ArrayList<protobuilder.Invoice>(orderHistory_);
        bitField0_ |= 0x00000080;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuilder.Invoice, protobuilder.Invoice.Builder, protobuilder.InvoiceOrBuilder> orderHistoryBuilder_;

    /**
     * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
     */
    public java.util.List<protobuilder.Invoice> getOrderHistoryList() {
      if (orderHistoryBuilder_ == null) {
        return java.util.Collections.unmodifiableList(orderHistory_);
      } else {
        return orderHistoryBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
     */
    public int getOrderHistoryCount() {
      if (orderHistoryBuilder_ == null) {
        return orderHistory_.size();
      } else {
        return orderHistoryBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
     */
    public protobuilder.Invoice getOrderHistory(int index) {
      if (orderHistoryBuilder_ == null) {
        return orderHistory_.get(index);
      } else {
        return orderHistoryBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
     */
    public Builder setOrderHistory(
        int index, protobuilder.Invoice value) {
      if (orderHistoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderHistoryIsMutable();
        orderHistory_.set(index, value);
        onChanged();
      } else {
        orderHistoryBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
     */
    public Builder setOrderHistory(
        int index, protobuilder.Invoice.Builder builderForValue) {
      if (orderHistoryBuilder_ == null) {
        ensureOrderHistoryIsMutable();
        orderHistory_.set(index, builderForValue.build());
        onChanged();
      } else {
        orderHistoryBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
     */
    public Builder addOrderHistory(protobuilder.Invoice value) {
      if (orderHistoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderHistoryIsMutable();
        orderHistory_.add(value);
        onChanged();
      } else {
        orderHistoryBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
     */
    public Builder addOrderHistory(
        int index, protobuilder.Invoice value) {
      if (orderHistoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderHistoryIsMutable();
        orderHistory_.add(index, value);
        onChanged();
      } else {
        orderHistoryBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
     */
    public Builder addOrderHistory(
        protobuilder.Invoice.Builder builderForValue) {
      if (orderHistoryBuilder_ == null) {
        ensureOrderHistoryIsMutable();
        orderHistory_.add(builderForValue.build());
        onChanged();
      } else {
        orderHistoryBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
     */
    public Builder addOrderHistory(
        int index, protobuilder.Invoice.Builder builderForValue) {
      if (orderHistoryBuilder_ == null) {
        ensureOrderHistoryIsMutable();
        orderHistory_.add(index, builderForValue.build());
        onChanged();
      } else {
        orderHistoryBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
     */
    public Builder addAllOrderHistory(
        java.lang.Iterable<? extends protobuilder.Invoice> values) {
      if (orderHistoryBuilder_ == null) {
        ensureOrderHistoryIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, orderHistory_);
        onChanged();
      } else {
        orderHistoryBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
     */
    public Builder clearOrderHistory() {
      if (orderHistoryBuilder_ == null) {
        orderHistory_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
      } else {
        orderHistoryBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
     */
    public Builder removeOrderHistory(int index) {
      if (orderHistoryBuilder_ == null) {
        ensureOrderHistoryIsMutable();
        orderHistory_.remove(index);
        onChanged();
      } else {
        orderHistoryBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
     */
    public protobuilder.Invoice.Builder getOrderHistoryBuilder(
        int index) {
      return getOrderHistoryFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
     */
    public protobuilder.InvoiceOrBuilder getOrderHistoryOrBuilder(
        int index) {
      if (orderHistoryBuilder_ == null) {
        return orderHistory_.get(index);  } else {
        return orderHistoryBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
     */
    public java.util.List<? extends protobuilder.InvoiceOrBuilder> 
         getOrderHistoryOrBuilderList() {
      if (orderHistoryBuilder_ != null) {
        return orderHistoryBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(orderHistory_);
      }
    }
    /**
     * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
     */
    public protobuilder.Invoice.Builder addOrderHistoryBuilder() {
      return getOrderHistoryFieldBuilder().addBuilder(
          protobuilder.Invoice.getDefaultInstance());
    }
    /**
     * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
     */
    public protobuilder.Invoice.Builder addOrderHistoryBuilder(
        int index) {
      return getOrderHistoryFieldBuilder().addBuilder(
          index, protobuilder.Invoice.getDefaultInstance());
    }
    /**
     * <code>repeated .Zkart.Invoice orderHistory = 8;</code>
     */
    public java.util.List<protobuilder.Invoice.Builder> 
         getOrderHistoryBuilderList() {
      return getOrderHistoryFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuilder.Invoice, protobuilder.Invoice.Builder, protobuilder.InvoiceOrBuilder> 
        getOrderHistoryFieldBuilder() {
      if (orderHistoryBuilder_ == null) {
        orderHistoryBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protobuilder.Invoice, protobuilder.Invoice.Builder, protobuilder.InvoiceOrBuilder>(
                orderHistory_,
                ((bitField0_ & 0x00000080) != 0),
                getParentForChildren(),
                isClean());
        orderHistory_ = null;
      }
      return orderHistoryBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Zkart.Customer)
  }

  // @@protoc_insertion_point(class_scope:Zkart.Customer)
  private static final protobuilder.Customer DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuilder.Customer();
  }

  public static protobuilder.Customer getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Customer>
      PARSER = new com.google.protobuf.AbstractParser<Customer>() {
    @java.lang.Override
    public Customer parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Customer(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Customer> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Customer> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protobuilder.Customer getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

