// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/Zkart.proto

package protobuilder;

public interface CustomersDBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Zkart.CustomersDB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Zkart.Customer customers = 1;</code>
   */
  java.util.List<protobuilder.Customer> 
      getCustomersList();
  /**
   * <code>repeated .Zkart.Customer customers = 1;</code>
   */
  protobuilder.Customer getCustomers(int index);
  /**
   * <code>repeated .Zkart.Customer customers = 1;</code>
   */
  int getCustomersCount();
  /**
   * <code>repeated .Zkart.Customer customers = 1;</code>
   */
  java.util.List<? extends protobuilder.CustomerOrBuilder> 
      getCustomersOrBuilderList();
  /**
   * <code>repeated .Zkart.Customer customers = 1;</code>
   */
  protobuilder.CustomerOrBuilder getCustomersOrBuilder(
      int index);
}
