// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/Zkart.proto

package protobuilder;

public interface DealsDBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Zkart.DealsDB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Zkart.Deal deals = 1;</code>
   */
  java.util.List<protobuilder.Deal> 
      getDealsList();
  /**
   * <code>repeated .Zkart.Deal deals = 1;</code>
   */
  protobuilder.Deal getDeals(int index);
  /**
   * <code>repeated .Zkart.Deal deals = 1;</code>
   */
  int getDealsCount();
  /**
   * <code>repeated .Zkart.Deal deals = 1;</code>
   */
  java.util.List<? extends protobuilder.DealOrBuilder> 
      getDealsOrBuilderList();
  /**
   * <code>repeated .Zkart.Deal deals = 1;</code>
   */
  protobuilder.DealOrBuilder getDealsOrBuilder(
      int index);
}
