// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/Zkart.proto

package protobuilder;

/**
 * Protobuf type {@code Zkart.DealsDB}
 */
public final class DealsDB extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Zkart.DealsDB)
    DealsDBOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DealsDB.newBuilder() to construct.
  private DealsDB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DealsDB() {
    deals_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DealsDB();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DealsDB(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              deals_ = new java.util.ArrayList<protobuilder.Deal>();
              mutable_bitField0_ |= 0x00000001;
            }
            deals_.add(
                input.readMessage(protobuilder.Deal.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        deals_ = java.util.Collections.unmodifiableList(deals_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuilder.ZkartProtos.internal_static_Zkart_DealsDB_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuilder.ZkartProtos.internal_static_Zkart_DealsDB_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuilder.DealsDB.class, protobuilder.DealsDB.Builder.class);
  }

  public static final int DEALS_FIELD_NUMBER = 1;
  private java.util.List<protobuilder.Deal> deals_;
  /**
   * <code>repeated .Zkart.Deal deals = 1;</code>
   */
  @java.lang.Override
  public java.util.List<protobuilder.Deal> getDealsList() {
    return deals_;
  }
  /**
   * <code>repeated .Zkart.Deal deals = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends protobuilder.DealOrBuilder> 
      getDealsOrBuilderList() {
    return deals_;
  }
  /**
   * <code>repeated .Zkart.Deal deals = 1;</code>
   */
  @java.lang.Override
  public int getDealsCount() {
    return deals_.size();
  }
  /**
   * <code>repeated .Zkart.Deal deals = 1;</code>
   */
  @java.lang.Override
  public protobuilder.Deal getDeals(int index) {
    return deals_.get(index);
  }
  /**
   * <code>repeated .Zkart.Deal deals = 1;</code>
   */
  @java.lang.Override
  public protobuilder.DealOrBuilder getDealsOrBuilder(
      int index) {
    return deals_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getDealsCount(); i++) {
      if (!getDeals(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < deals_.size(); i++) {
      output.writeMessage(1, deals_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < deals_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, deals_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuilder.DealsDB)) {
      return super.equals(obj);
    }
    protobuilder.DealsDB other = (protobuilder.DealsDB) obj;

    if (!getDealsList()
        .equals(other.getDealsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDealsCount() > 0) {
      hash = (37 * hash) + DEALS_FIELD_NUMBER;
      hash = (53 * hash) + getDealsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuilder.DealsDB parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuilder.DealsDB parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuilder.DealsDB parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuilder.DealsDB parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuilder.DealsDB parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuilder.DealsDB parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuilder.DealsDB parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuilder.DealsDB parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuilder.DealsDB parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuilder.DealsDB parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuilder.DealsDB parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuilder.DealsDB parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuilder.DealsDB prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Zkart.DealsDB}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Zkart.DealsDB)
      protobuilder.DealsDBOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuilder.ZkartProtos.internal_static_Zkart_DealsDB_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuilder.ZkartProtos.internal_static_Zkart_DealsDB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuilder.DealsDB.class, protobuilder.DealsDB.Builder.class);
    }

    // Construct using protobuilder.DealsDB.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDealsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (dealsBuilder_ == null) {
        deals_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        dealsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuilder.ZkartProtos.internal_static_Zkart_DealsDB_descriptor;
    }

    @java.lang.Override
    public protobuilder.DealsDB getDefaultInstanceForType() {
      return protobuilder.DealsDB.getDefaultInstance();
    }

    @java.lang.Override
    public protobuilder.DealsDB build() {
      protobuilder.DealsDB result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protobuilder.DealsDB buildPartial() {
      protobuilder.DealsDB result = new protobuilder.DealsDB(this);
      int from_bitField0_ = bitField0_;
      if (dealsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          deals_ = java.util.Collections.unmodifiableList(deals_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.deals_ = deals_;
      } else {
        result.deals_ = dealsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuilder.DealsDB) {
        return mergeFrom((protobuilder.DealsDB)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuilder.DealsDB other) {
      if (other == protobuilder.DealsDB.getDefaultInstance()) return this;
      if (dealsBuilder_ == null) {
        if (!other.deals_.isEmpty()) {
          if (deals_.isEmpty()) {
            deals_ = other.deals_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDealsIsMutable();
            deals_.addAll(other.deals_);
          }
          onChanged();
        }
      } else {
        if (!other.deals_.isEmpty()) {
          if (dealsBuilder_.isEmpty()) {
            dealsBuilder_.dispose();
            dealsBuilder_ = null;
            deals_ = other.deals_;
            bitField0_ = (bitField0_ & ~0x00000001);
            dealsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDealsFieldBuilder() : null;
          } else {
            dealsBuilder_.addAllMessages(other.deals_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      for (int i = 0; i < getDealsCount(); i++) {
        if (!getDeals(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuilder.DealsDB parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuilder.DealsDB) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<protobuilder.Deal> deals_ =
      java.util.Collections.emptyList();
    private void ensureDealsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        deals_ = new java.util.ArrayList<protobuilder.Deal>(deals_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuilder.Deal, protobuilder.Deal.Builder, protobuilder.DealOrBuilder> dealsBuilder_;

    /**
     * <code>repeated .Zkart.Deal deals = 1;</code>
     */
    public java.util.List<protobuilder.Deal> getDealsList() {
      if (dealsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(deals_);
      } else {
        return dealsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Zkart.Deal deals = 1;</code>
     */
    public int getDealsCount() {
      if (dealsBuilder_ == null) {
        return deals_.size();
      } else {
        return dealsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Zkart.Deal deals = 1;</code>
     */
    public protobuilder.Deal getDeals(int index) {
      if (dealsBuilder_ == null) {
        return deals_.get(index);
      } else {
        return dealsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Zkart.Deal deals = 1;</code>
     */
    public Builder setDeals(
        int index, protobuilder.Deal value) {
      if (dealsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDealsIsMutable();
        deals_.set(index, value);
        onChanged();
      } else {
        dealsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Deal deals = 1;</code>
     */
    public Builder setDeals(
        int index, protobuilder.Deal.Builder builderForValue) {
      if (dealsBuilder_ == null) {
        ensureDealsIsMutable();
        deals_.set(index, builderForValue.build());
        onChanged();
      } else {
        dealsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Deal deals = 1;</code>
     */
    public Builder addDeals(protobuilder.Deal value) {
      if (dealsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDealsIsMutable();
        deals_.add(value);
        onChanged();
      } else {
        dealsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Deal deals = 1;</code>
     */
    public Builder addDeals(
        int index, protobuilder.Deal value) {
      if (dealsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDealsIsMutable();
        deals_.add(index, value);
        onChanged();
      } else {
        dealsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Deal deals = 1;</code>
     */
    public Builder addDeals(
        protobuilder.Deal.Builder builderForValue) {
      if (dealsBuilder_ == null) {
        ensureDealsIsMutable();
        deals_.add(builderForValue.build());
        onChanged();
      } else {
        dealsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Deal deals = 1;</code>
     */
    public Builder addDeals(
        int index, protobuilder.Deal.Builder builderForValue) {
      if (dealsBuilder_ == null) {
        ensureDealsIsMutable();
        deals_.add(index, builderForValue.build());
        onChanged();
      } else {
        dealsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Deal deals = 1;</code>
     */
    public Builder addAllDeals(
        java.lang.Iterable<? extends protobuilder.Deal> values) {
      if (dealsBuilder_ == null) {
        ensureDealsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, deals_);
        onChanged();
      } else {
        dealsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Deal deals = 1;</code>
     */
    public Builder clearDeals() {
      if (dealsBuilder_ == null) {
        deals_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        dealsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Deal deals = 1;</code>
     */
    public Builder removeDeals(int index) {
      if (dealsBuilder_ == null) {
        ensureDealsIsMutable();
        deals_.remove(index);
        onChanged();
      } else {
        dealsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Deal deals = 1;</code>
     */
    public protobuilder.Deal.Builder getDealsBuilder(
        int index) {
      return getDealsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Zkart.Deal deals = 1;</code>
     */
    public protobuilder.DealOrBuilder getDealsOrBuilder(
        int index) {
      if (dealsBuilder_ == null) {
        return deals_.get(index);  } else {
        return dealsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Zkart.Deal deals = 1;</code>
     */
    public java.util.List<? extends protobuilder.DealOrBuilder> 
         getDealsOrBuilderList() {
      if (dealsBuilder_ != null) {
        return dealsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(deals_);
      }
    }
    /**
     * <code>repeated .Zkart.Deal deals = 1;</code>
     */
    public protobuilder.Deal.Builder addDealsBuilder() {
      return getDealsFieldBuilder().addBuilder(
          protobuilder.Deal.getDefaultInstance());
    }
    /**
     * <code>repeated .Zkart.Deal deals = 1;</code>
     */
    public protobuilder.Deal.Builder addDealsBuilder(
        int index) {
      return getDealsFieldBuilder().addBuilder(
          index, protobuilder.Deal.getDefaultInstance());
    }
    /**
     * <code>repeated .Zkart.Deal deals = 1;</code>
     */
    public java.util.List<protobuilder.Deal.Builder> 
         getDealsBuilderList() {
      return getDealsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuilder.Deal, protobuilder.Deal.Builder, protobuilder.DealOrBuilder> 
        getDealsFieldBuilder() {
      if (dealsBuilder_ == null) {
        dealsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protobuilder.Deal, protobuilder.Deal.Builder, protobuilder.DealOrBuilder>(
                deals_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        deals_ = null;
      }
      return dealsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Zkart.DealsDB)
  }

  // @@protoc_insertion_point(class_scope:Zkart.DealsDB)
  private static final protobuilder.DealsDB DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuilder.DealsDB();
  }

  public static protobuilder.DealsDB getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<DealsDB>
      PARSER = new com.google.protobuf.AbstractParser<DealsDB>() {
    @java.lang.Override
    public DealsDB parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DealsDB(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DealsDB> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DealsDB> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protobuilder.DealsDB getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

