// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/Zkart.proto

package protobuilder;

public interface DealOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Zkart.Deal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>required int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>optional string status = 2;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>optional string status = 2;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>optional string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>required string dealName = 3;</code>
   * @return Whether the dealName field is set.
   */
  boolean hasDealName();
  /**
   * <code>required string dealName = 3;</code>
   * @return The dealName.
   */
  java.lang.String getDealName();
  /**
   * <code>required string dealName = 3;</code>
   * @return The bytes for dealName.
   */
  com.google.protobuf.ByteString
      getDealNameBytes();

  /**
   * <code>required string discountCode = 4;</code>
   * @return Whether the discountCode field is set.
   */
  boolean hasDiscountCode();
  /**
   * <code>required string discountCode = 4;</code>
   * @return The discountCode.
   */
  java.lang.String getDiscountCode();
  /**
   * <code>required string discountCode = 4;</code>
   * @return The bytes for discountCode.
   */
  com.google.protobuf.ByteString
      getDiscountCodeBytes();

  /**
   * <code>required double discountPercent = 5;</code>
   * @return Whether the discountPercent field is set.
   */
  boolean hasDiscountPercent();
  /**
   * <code>required double discountPercent = 5;</code>
   * @return The discountPercent.
   */
  double getDiscountPercent();

  /**
   * <code>required int32 ordersAfterDealExpires = 6;</code>
   * @return Whether the ordersAfterDealExpires field is set.
   */
  boolean hasOrdersAfterDealExpires();
  /**
   * <code>required int32 ordersAfterDealExpires = 6;</code>
   * @return The ordersAfterDealExpires.
   */
  int getOrdersAfterDealExpires();

  /**
   * <code>optional int32 lastValidInvoiceNumber = 7;</code>
   * @return Whether the lastValidInvoiceNumber field is set.
   */
  boolean hasLastValidInvoiceNumber();
  /**
   * <code>optional int32 lastValidInvoiceNumber = 7;</code>
   * @return The lastValidInvoiceNumber.
   */
  int getLastValidInvoiceNumber();
}
