// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/Zkart.proto

package protobuilder;

/**
 * Protobuf type {@code Zkart.Deal}
 */
public final class Deal extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Zkart.Deal)
    DealOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Deal.newBuilder() to construct.
  private Deal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Deal() {
    status_ = "";
    dealName_ = "";
    discountCode_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Deal();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Deal(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            id_ = input.readInt64();
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            status_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            dealName_ = bs;
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            discountCode_ = bs;
            break;
          }
          case 41: {
            bitField0_ |= 0x00000010;
            discountPercent_ = input.readDouble();
            break;
          }
          case 48: {
            bitField0_ |= 0x00000020;
            ordersAfterDealExpires_ = input.readInt32();
            break;
          }
          case 56: {
            bitField0_ |= 0x00000040;
            lastValidInvoiceNumber_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuilder.ZkartProtos.internal_static_Zkart_Deal_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuilder.ZkartProtos.internal_static_Zkart_Deal_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuilder.Deal.class, protobuilder.Deal.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>required int64 id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private volatile java.lang.Object status_;
  /**
   * <code>optional string status = 2;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string status = 2;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        status_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string status = 2;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEALNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object dealName_;
  /**
   * <code>required string dealName = 3;</code>
   * @return Whether the dealName field is set.
   */
  @java.lang.Override
  public boolean hasDealName() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required string dealName = 3;</code>
   * @return The dealName.
   */
  @java.lang.Override
  public java.lang.String getDealName() {
    java.lang.Object ref = dealName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        dealName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string dealName = 3;</code>
   * @return The bytes for dealName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDealNameBytes() {
    java.lang.Object ref = dealName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dealName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISCOUNTCODE_FIELD_NUMBER = 4;
  private volatile java.lang.Object discountCode_;
  /**
   * <code>required string discountCode = 4;</code>
   * @return Whether the discountCode field is set.
   */
  @java.lang.Override
  public boolean hasDiscountCode() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>required string discountCode = 4;</code>
   * @return The discountCode.
   */
  @java.lang.Override
  public java.lang.String getDiscountCode() {
    java.lang.Object ref = discountCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        discountCode_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string discountCode = 4;</code>
   * @return The bytes for discountCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDiscountCodeBytes() {
    java.lang.Object ref = discountCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      discountCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISCOUNTPERCENT_FIELD_NUMBER = 5;
  private double discountPercent_;
  /**
   * <code>required double discountPercent = 5;</code>
   * @return Whether the discountPercent field is set.
   */
  @java.lang.Override
  public boolean hasDiscountPercent() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>required double discountPercent = 5;</code>
   * @return The discountPercent.
   */
  @java.lang.Override
  public double getDiscountPercent() {
    return discountPercent_;
  }

  public static final int ORDERSAFTERDEALEXPIRES_FIELD_NUMBER = 6;
  private int ordersAfterDealExpires_;
  /**
   * <code>required int32 ordersAfterDealExpires = 6;</code>
   * @return Whether the ordersAfterDealExpires field is set.
   */
  @java.lang.Override
  public boolean hasOrdersAfterDealExpires() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>required int32 ordersAfterDealExpires = 6;</code>
   * @return The ordersAfterDealExpires.
   */
  @java.lang.Override
  public int getOrdersAfterDealExpires() {
    return ordersAfterDealExpires_;
  }

  public static final int LASTVALIDINVOICENUMBER_FIELD_NUMBER = 7;
  private int lastValidInvoiceNumber_;
  /**
   * <code>optional int32 lastValidInvoiceNumber = 7;</code>
   * @return Whether the lastValidInvoiceNumber field is set.
   */
  @java.lang.Override
  public boolean hasLastValidInvoiceNumber() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional int32 lastValidInvoiceNumber = 7;</code>
   * @return The lastValidInvoiceNumber.
   */
  @java.lang.Override
  public int getLastValidInvoiceNumber() {
    return lastValidInvoiceNumber_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasDealName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasDiscountCode()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasDiscountPercent()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasOrdersAfterDealExpires()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt64(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, status_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dealName_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, discountCode_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeDouble(5, discountPercent_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeInt32(6, ordersAfterDealExpires_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeInt32(7, lastValidInvoiceNumber_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, status_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dealName_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, discountCode_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, discountPercent_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, ordersAfterDealExpires_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, lastValidInvoiceNumber_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuilder.Deal)) {
      return super.equals(obj);
    }
    protobuilder.Deal other = (protobuilder.Deal) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (getId()
          != other.getId()) return false;
    }
    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (hasDealName() != other.hasDealName()) return false;
    if (hasDealName()) {
      if (!getDealName()
          .equals(other.getDealName())) return false;
    }
    if (hasDiscountCode() != other.hasDiscountCode()) return false;
    if (hasDiscountCode()) {
      if (!getDiscountCode()
          .equals(other.getDiscountCode())) return false;
    }
    if (hasDiscountPercent() != other.hasDiscountPercent()) return false;
    if (hasDiscountPercent()) {
      if (java.lang.Double.doubleToLongBits(getDiscountPercent())
          != java.lang.Double.doubleToLongBits(
              other.getDiscountPercent())) return false;
    }
    if (hasOrdersAfterDealExpires() != other.hasOrdersAfterDealExpires()) return false;
    if (hasOrdersAfterDealExpires()) {
      if (getOrdersAfterDealExpires()
          != other.getOrdersAfterDealExpires()) return false;
    }
    if (hasLastValidInvoiceNumber() != other.hasLastValidInvoiceNumber()) return false;
    if (hasLastValidInvoiceNumber()) {
      if (getLastValidInvoiceNumber()
          != other.getLastValidInvoiceNumber()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
    }
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    if (hasDealName()) {
      hash = (37 * hash) + DEALNAME_FIELD_NUMBER;
      hash = (53 * hash) + getDealName().hashCode();
    }
    if (hasDiscountCode()) {
      hash = (37 * hash) + DISCOUNTCODE_FIELD_NUMBER;
      hash = (53 * hash) + getDiscountCode().hashCode();
    }
    if (hasDiscountPercent()) {
      hash = (37 * hash) + DISCOUNTPERCENT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDiscountPercent()));
    }
    if (hasOrdersAfterDealExpires()) {
      hash = (37 * hash) + ORDERSAFTERDEALEXPIRES_FIELD_NUMBER;
      hash = (53 * hash) + getOrdersAfterDealExpires();
    }
    if (hasLastValidInvoiceNumber()) {
      hash = (37 * hash) + LASTVALIDINVOICENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getLastValidInvoiceNumber();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuilder.Deal parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuilder.Deal parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuilder.Deal parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuilder.Deal parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuilder.Deal parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuilder.Deal parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuilder.Deal parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuilder.Deal parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuilder.Deal parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuilder.Deal parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuilder.Deal parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuilder.Deal parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuilder.Deal prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Zkart.Deal}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Zkart.Deal)
      protobuilder.DealOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuilder.ZkartProtos.internal_static_Zkart_Deal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuilder.ZkartProtos.internal_static_Zkart_Deal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuilder.Deal.class, protobuilder.Deal.Builder.class);
    }

    // Construct using protobuilder.Deal.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      dealName_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      discountCode_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      discountPercent_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000010);
      ordersAfterDealExpires_ = 0;
      bitField0_ = (bitField0_ & ~0x00000020);
      lastValidInvoiceNumber_ = 0;
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuilder.ZkartProtos.internal_static_Zkart_Deal_descriptor;
    }

    @java.lang.Override
    public protobuilder.Deal getDefaultInstanceForType() {
      return protobuilder.Deal.getDefaultInstance();
    }

    @java.lang.Override
    public protobuilder.Deal build() {
      protobuilder.Deal result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protobuilder.Deal buildPartial() {
      protobuilder.Deal result = new protobuilder.Deal(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.status_ = status_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.dealName_ = dealName_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.discountCode_ = discountCode_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.discountPercent_ = discountPercent_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.ordersAfterDealExpires_ = ordersAfterDealExpires_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.lastValidInvoiceNumber_ = lastValidInvoiceNumber_;
        to_bitField0_ |= 0x00000040;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuilder.Deal) {
        return mergeFrom((protobuilder.Deal)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuilder.Deal other) {
      if (other == protobuilder.Deal.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasStatus()) {
        bitField0_ |= 0x00000002;
        status_ = other.status_;
        onChanged();
      }
      if (other.hasDealName()) {
        bitField0_ |= 0x00000004;
        dealName_ = other.dealName_;
        onChanged();
      }
      if (other.hasDiscountCode()) {
        bitField0_ |= 0x00000008;
        discountCode_ = other.discountCode_;
        onChanged();
      }
      if (other.hasDiscountPercent()) {
        setDiscountPercent(other.getDiscountPercent());
      }
      if (other.hasOrdersAfterDealExpires()) {
        setOrdersAfterDealExpires(other.getOrdersAfterDealExpires());
      }
      if (other.hasLastValidInvoiceNumber()) {
        setLastValidInvoiceNumber(other.getLastValidInvoiceNumber());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasId()) {
        return false;
      }
      if (!hasDealName()) {
        return false;
      }
      if (!hasDiscountCode()) {
        return false;
      }
      if (!hasDiscountPercent()) {
        return false;
      }
      if (!hasOrdersAfterDealExpires()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuilder.Deal parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuilder.Deal) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>required int64 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>required int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>optional string status = 2;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string status = 2;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          status_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string status = 2;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string status = 2;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string status = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000002);
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <code>optional string status = 2;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      status_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dealName_ = "";
    /**
     * <code>required string dealName = 3;</code>
     * @return Whether the dealName field is set.
     */
    public boolean hasDealName() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string dealName = 3;</code>
     * @return The dealName.
     */
    public java.lang.String getDealName() {
      java.lang.Object ref = dealName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dealName_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string dealName = 3;</code>
     * @return The bytes for dealName.
     */
    public com.google.protobuf.ByteString
        getDealNameBytes() {
      java.lang.Object ref = dealName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dealName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string dealName = 3;</code>
     * @param value The dealName to set.
     * @return This builder for chaining.
     */
    public Builder setDealName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      dealName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string dealName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDealName() {
      bitField0_ = (bitField0_ & ~0x00000004);
      dealName_ = getDefaultInstance().getDealName();
      onChanged();
      return this;
    }
    /**
     * <code>required string dealName = 3;</code>
     * @param value The bytes for dealName to set.
     * @return This builder for chaining.
     */
    public Builder setDealNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      dealName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object discountCode_ = "";
    /**
     * <code>required string discountCode = 4;</code>
     * @return Whether the discountCode field is set.
     */
    public boolean hasDiscountCode() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string discountCode = 4;</code>
     * @return The discountCode.
     */
    public java.lang.String getDiscountCode() {
      java.lang.Object ref = discountCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          discountCode_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string discountCode = 4;</code>
     * @return The bytes for discountCode.
     */
    public com.google.protobuf.ByteString
        getDiscountCodeBytes() {
      java.lang.Object ref = discountCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        discountCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string discountCode = 4;</code>
     * @param value The discountCode to set.
     * @return This builder for chaining.
     */
    public Builder setDiscountCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      discountCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string discountCode = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDiscountCode() {
      bitField0_ = (bitField0_ & ~0x00000008);
      discountCode_ = getDefaultInstance().getDiscountCode();
      onChanged();
      return this;
    }
    /**
     * <code>required string discountCode = 4;</code>
     * @param value The bytes for discountCode to set.
     * @return This builder for chaining.
     */
    public Builder setDiscountCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      discountCode_ = value;
      onChanged();
      return this;
    }

    private double discountPercent_ ;
    /**
     * <code>required double discountPercent = 5;</code>
     * @return Whether the discountPercent field is set.
     */
    @java.lang.Override
    public boolean hasDiscountPercent() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required double discountPercent = 5;</code>
     * @return The discountPercent.
     */
    @java.lang.Override
    public double getDiscountPercent() {
      return discountPercent_;
    }
    /**
     * <code>required double discountPercent = 5;</code>
     * @param value The discountPercent to set.
     * @return This builder for chaining.
     */
    public Builder setDiscountPercent(double value) {
      bitField0_ |= 0x00000010;
      discountPercent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required double discountPercent = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDiscountPercent() {
      bitField0_ = (bitField0_ & ~0x00000010);
      discountPercent_ = 0D;
      onChanged();
      return this;
    }

    private int ordersAfterDealExpires_ ;
    /**
     * <code>required int32 ordersAfterDealExpires = 6;</code>
     * @return Whether the ordersAfterDealExpires field is set.
     */
    @java.lang.Override
    public boolean hasOrdersAfterDealExpires() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required int32 ordersAfterDealExpires = 6;</code>
     * @return The ordersAfterDealExpires.
     */
    @java.lang.Override
    public int getOrdersAfterDealExpires() {
      return ordersAfterDealExpires_;
    }
    /**
     * <code>required int32 ordersAfterDealExpires = 6;</code>
     * @param value The ordersAfterDealExpires to set.
     * @return This builder for chaining.
     */
    public Builder setOrdersAfterDealExpires(int value) {
      bitField0_ |= 0x00000020;
      ordersAfterDealExpires_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 ordersAfterDealExpires = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrdersAfterDealExpires() {
      bitField0_ = (bitField0_ & ~0x00000020);
      ordersAfterDealExpires_ = 0;
      onChanged();
      return this;
    }

    private int lastValidInvoiceNumber_ ;
    /**
     * <code>optional int32 lastValidInvoiceNumber = 7;</code>
     * @return Whether the lastValidInvoiceNumber field is set.
     */
    @java.lang.Override
    public boolean hasLastValidInvoiceNumber() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional int32 lastValidInvoiceNumber = 7;</code>
     * @return The lastValidInvoiceNumber.
     */
    @java.lang.Override
    public int getLastValidInvoiceNumber() {
      return lastValidInvoiceNumber_;
    }
    /**
     * <code>optional int32 lastValidInvoiceNumber = 7;</code>
     * @param value The lastValidInvoiceNumber to set.
     * @return This builder for chaining.
     */
    public Builder setLastValidInvoiceNumber(int value) {
      bitField0_ |= 0x00000040;
      lastValidInvoiceNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 lastValidInvoiceNumber = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastValidInvoiceNumber() {
      bitField0_ = (bitField0_ & ~0x00000040);
      lastValidInvoiceNumber_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Zkart.Deal)
  }

  // @@protoc_insertion_point(class_scope:Zkart.Deal)
  private static final protobuilder.Deal DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuilder.Deal();
  }

  public static protobuilder.Deal getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Deal>
      PARSER = new com.google.protobuf.AbstractParser<Deal>() {
    @java.lang.Override
    public Deal parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Deal(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Deal> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Deal> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protobuilder.Deal getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

