// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/Zkart.proto

package protobuilder;

public interface InventoryDBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Zkart.InventoryDB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Zkart.Product products = 1;</code>
   */
  java.util.List<protobuilder.Product> 
      getProductsList();
  /**
   * <code>repeated .Zkart.Product products = 1;</code>
   */
  protobuilder.Product getProducts(int index);
  /**
   * <code>repeated .Zkart.Product products = 1;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .Zkart.Product products = 1;</code>
   */
  java.util.List<? extends protobuilder.ProductOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .Zkart.Product products = 1;</code>
   */
  protobuilder.ProductOrBuilder getProductsOrBuilder(
      int index);
}
