// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/Zkart.proto

package protobuilder;

/**
 * Protobuf type {@code Zkart.Invoice}
 */
public final class Invoice extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Zkart.Invoice)
    InvoiceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Invoice.newBuilder() to construct.
  private Invoice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Invoice() {
    date_ = "";
    lineItems_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Invoice();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Invoice(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            id_ = input.readInt64();
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            date_ = bs;
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            customerID_ = input.readInt64();
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              lineItems_ = new java.util.ArrayList<protobuilder.LineItem>();
              mutable_bitField0_ |= 0x00000008;
            }
            lineItems_.add(
                input.readMessage(protobuilder.LineItem.PARSER, extensionRegistry));
            break;
          }
          case 41: {
            bitField0_ |= 0x00000008;
            subTotal_ = input.readDouble();
            break;
          }
          case 49: {
            bitField0_ |= 0x00000010;
            discount_ = input.readDouble();
            break;
          }
          case 57: {
            bitField0_ |= 0x00000020;
            total_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) != 0)) {
        lineItems_ = java.util.Collections.unmodifiableList(lineItems_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuilder.ZkartProtos.internal_static_Zkart_Invoice_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuilder.ZkartProtos.internal_static_Zkart_Invoice_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuilder.Invoice.class, protobuilder.Invoice.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>required int64 id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int DATE_FIELD_NUMBER = 2;
  private volatile java.lang.Object date_;
  /**
   * <code>required string date = 2;</code>
   * @return Whether the date field is set.
   */
  @java.lang.Override
  public boolean hasDate() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required string date = 2;</code>
   * @return The date.
   */
  @java.lang.Override
  public java.lang.String getDate() {
    java.lang.Object ref = date_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        date_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string date = 2;</code>
   * @return The bytes for date.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDateBytes() {
    java.lang.Object ref = date_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      date_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CUSTOMERID_FIELD_NUMBER = 3;
  private long customerID_;
  /**
   * <code>required int64 customerID = 3;</code>
   * @return Whether the customerID field is set.
   */
  @java.lang.Override
  public boolean hasCustomerID() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required int64 customerID = 3;</code>
   * @return The customerID.
   */
  @java.lang.Override
  public long getCustomerID() {
    return customerID_;
  }

  public static final int LINEITEMS_FIELD_NUMBER = 4;
  private java.util.List<protobuilder.LineItem> lineItems_;
  /**
   * <code>repeated .Zkart.LineItem lineItems = 4;</code>
   */
  @java.lang.Override
  public java.util.List<protobuilder.LineItem> getLineItemsList() {
    return lineItems_;
  }
  /**
   * <code>repeated .Zkart.LineItem lineItems = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends protobuilder.LineItemOrBuilder> 
      getLineItemsOrBuilderList() {
    return lineItems_;
  }
  /**
   * <code>repeated .Zkart.LineItem lineItems = 4;</code>
   */
  @java.lang.Override
  public int getLineItemsCount() {
    return lineItems_.size();
  }
  /**
   * <code>repeated .Zkart.LineItem lineItems = 4;</code>
   */
  @java.lang.Override
  public protobuilder.LineItem getLineItems(int index) {
    return lineItems_.get(index);
  }
  /**
   * <code>repeated .Zkart.LineItem lineItems = 4;</code>
   */
  @java.lang.Override
  public protobuilder.LineItemOrBuilder getLineItemsOrBuilder(
      int index) {
    return lineItems_.get(index);
  }

  public static final int SUBTOTAL_FIELD_NUMBER = 5;
  private double subTotal_;
  /**
   * <code>required double subTotal = 5;</code>
   * @return Whether the subTotal field is set.
   */
  @java.lang.Override
  public boolean hasSubTotal() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>required double subTotal = 5;</code>
   * @return The subTotal.
   */
  @java.lang.Override
  public double getSubTotal() {
    return subTotal_;
  }

  public static final int DISCOUNT_FIELD_NUMBER = 6;
  private double discount_;
  /**
   * <code>optional double discount = 6;</code>
   * @return Whether the discount field is set.
   */
  @java.lang.Override
  public boolean hasDiscount() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional double discount = 6;</code>
   * @return The discount.
   */
  @java.lang.Override
  public double getDiscount() {
    return discount_;
  }

  public static final int TOTAL_FIELD_NUMBER = 7;
  private double total_;
  /**
   * <code>required double total = 7;</code>
   * @return Whether the total field is set.
   */
  @java.lang.Override
  public boolean hasTotal() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>required double total = 7;</code>
   * @return The total.
   */
  @java.lang.Override
  public double getTotal() {
    return total_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasDate()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasCustomerID()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasSubTotal()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasTotal()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getLineItemsCount(); i++) {
      if (!getLineItems(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt64(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, date_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt64(3, customerID_);
    }
    for (int i = 0; i < lineItems_.size(); i++) {
      output.writeMessage(4, lineItems_.get(i));
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeDouble(5, subTotal_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeDouble(6, discount_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeDouble(7, total_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, date_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, customerID_);
    }
    for (int i = 0; i < lineItems_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, lineItems_.get(i));
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, subTotal_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, discount_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, total_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuilder.Invoice)) {
      return super.equals(obj);
    }
    protobuilder.Invoice other = (protobuilder.Invoice) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (getId()
          != other.getId()) return false;
    }
    if (hasDate() != other.hasDate()) return false;
    if (hasDate()) {
      if (!getDate()
          .equals(other.getDate())) return false;
    }
    if (hasCustomerID() != other.hasCustomerID()) return false;
    if (hasCustomerID()) {
      if (getCustomerID()
          != other.getCustomerID()) return false;
    }
    if (!getLineItemsList()
        .equals(other.getLineItemsList())) return false;
    if (hasSubTotal() != other.hasSubTotal()) return false;
    if (hasSubTotal()) {
      if (java.lang.Double.doubleToLongBits(getSubTotal())
          != java.lang.Double.doubleToLongBits(
              other.getSubTotal())) return false;
    }
    if (hasDiscount() != other.hasDiscount()) return false;
    if (hasDiscount()) {
      if (java.lang.Double.doubleToLongBits(getDiscount())
          != java.lang.Double.doubleToLongBits(
              other.getDiscount())) return false;
    }
    if (hasTotal() != other.hasTotal()) return false;
    if (hasTotal()) {
      if (java.lang.Double.doubleToLongBits(getTotal())
          != java.lang.Double.doubleToLongBits(
              other.getTotal())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
    }
    if (hasDate()) {
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
    }
    if (hasCustomerID()) {
      hash = (37 * hash) + CUSTOMERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCustomerID());
    }
    if (getLineItemsCount() > 0) {
      hash = (37 * hash) + LINEITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getLineItemsList().hashCode();
    }
    if (hasSubTotal()) {
      hash = (37 * hash) + SUBTOTAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSubTotal()));
    }
    if (hasDiscount()) {
      hash = (37 * hash) + DISCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDiscount()));
    }
    if (hasTotal()) {
      hash = (37 * hash) + TOTAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTotal()));
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuilder.Invoice parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuilder.Invoice parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuilder.Invoice parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuilder.Invoice parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuilder.Invoice parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuilder.Invoice parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuilder.Invoice parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuilder.Invoice parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuilder.Invoice parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuilder.Invoice parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuilder.Invoice parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuilder.Invoice parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuilder.Invoice prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Zkart.Invoice}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Zkart.Invoice)
      protobuilder.InvoiceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuilder.ZkartProtos.internal_static_Zkart_Invoice_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuilder.ZkartProtos.internal_static_Zkart_Invoice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuilder.Invoice.class, protobuilder.Invoice.Builder.class);
    }

    // Construct using protobuilder.Invoice.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getLineItemsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      date_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      customerID_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      if (lineItemsBuilder_ == null) {
        lineItems_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        lineItemsBuilder_.clear();
      }
      subTotal_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000010);
      discount_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000020);
      total_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuilder.ZkartProtos.internal_static_Zkart_Invoice_descriptor;
    }

    @java.lang.Override
    public protobuilder.Invoice getDefaultInstanceForType() {
      return protobuilder.Invoice.getDefaultInstance();
    }

    @java.lang.Override
    public protobuilder.Invoice build() {
      protobuilder.Invoice result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protobuilder.Invoice buildPartial() {
      protobuilder.Invoice result = new protobuilder.Invoice(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.date_ = date_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.customerID_ = customerID_;
        to_bitField0_ |= 0x00000004;
      }
      if (lineItemsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          lineItems_ = java.util.Collections.unmodifiableList(lineItems_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.lineItems_ = lineItems_;
      } else {
        result.lineItems_ = lineItemsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.subTotal_ = subTotal_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.discount_ = discount_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.total_ = total_;
        to_bitField0_ |= 0x00000020;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuilder.Invoice) {
        return mergeFrom((protobuilder.Invoice)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuilder.Invoice other) {
      if (other == protobuilder.Invoice.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasDate()) {
        bitField0_ |= 0x00000002;
        date_ = other.date_;
        onChanged();
      }
      if (other.hasCustomerID()) {
        setCustomerID(other.getCustomerID());
      }
      if (lineItemsBuilder_ == null) {
        if (!other.lineItems_.isEmpty()) {
          if (lineItems_.isEmpty()) {
            lineItems_ = other.lineItems_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureLineItemsIsMutable();
            lineItems_.addAll(other.lineItems_);
          }
          onChanged();
        }
      } else {
        if (!other.lineItems_.isEmpty()) {
          if (lineItemsBuilder_.isEmpty()) {
            lineItemsBuilder_.dispose();
            lineItemsBuilder_ = null;
            lineItems_ = other.lineItems_;
            bitField0_ = (bitField0_ & ~0x00000008);
            lineItemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getLineItemsFieldBuilder() : null;
          } else {
            lineItemsBuilder_.addAllMessages(other.lineItems_);
          }
        }
      }
      if (other.hasSubTotal()) {
        setSubTotal(other.getSubTotal());
      }
      if (other.hasDiscount()) {
        setDiscount(other.getDiscount());
      }
      if (other.hasTotal()) {
        setTotal(other.getTotal());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasId()) {
        return false;
      }
      if (!hasDate()) {
        return false;
      }
      if (!hasCustomerID()) {
        return false;
      }
      if (!hasSubTotal()) {
        return false;
      }
      if (!hasTotal()) {
        return false;
      }
      for (int i = 0; i < getLineItemsCount(); i++) {
        if (!getLineItems(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuilder.Invoice parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuilder.Invoice) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>required int64 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>required int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object date_ = "";
    /**
     * <code>required string date = 2;</code>
     * @return Whether the date field is set.
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string date = 2;</code>
     * @return The date.
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          date_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string date = 2;</code>
     * @return The bytes for date.
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string date = 2;</code>
     * @param value The date to set.
     * @return This builder for chaining.
     */
    public Builder setDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      date_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string date = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDate() {
      bitField0_ = (bitField0_ & ~0x00000002);
      date_ = getDefaultInstance().getDate();
      onChanged();
      return this;
    }
    /**
     * <code>required string date = 2;</code>
     * @param value The bytes for date to set.
     * @return This builder for chaining.
     */
    public Builder setDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      date_ = value;
      onChanged();
      return this;
    }

    private long customerID_ ;
    /**
     * <code>required int64 customerID = 3;</code>
     * @return Whether the customerID field is set.
     */
    @java.lang.Override
    public boolean hasCustomerID() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int64 customerID = 3;</code>
     * @return The customerID.
     */
    @java.lang.Override
    public long getCustomerID() {
      return customerID_;
    }
    /**
     * <code>required int64 customerID = 3;</code>
     * @param value The customerID to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerID(long value) {
      bitField0_ |= 0x00000004;
      customerID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 customerID = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCustomerID() {
      bitField0_ = (bitField0_ & ~0x00000004);
      customerID_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<protobuilder.LineItem> lineItems_ =
      java.util.Collections.emptyList();
    private void ensureLineItemsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        lineItems_ = new java.util.ArrayList<protobuilder.LineItem>(lineItems_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuilder.LineItem, protobuilder.LineItem.Builder, protobuilder.LineItemOrBuilder> lineItemsBuilder_;

    /**
     * <code>repeated .Zkart.LineItem lineItems = 4;</code>
     */
    public java.util.List<protobuilder.LineItem> getLineItemsList() {
      if (lineItemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(lineItems_);
      } else {
        return lineItemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Zkart.LineItem lineItems = 4;</code>
     */
    public int getLineItemsCount() {
      if (lineItemsBuilder_ == null) {
        return lineItems_.size();
      } else {
        return lineItemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Zkart.LineItem lineItems = 4;</code>
     */
    public protobuilder.LineItem getLineItems(int index) {
      if (lineItemsBuilder_ == null) {
        return lineItems_.get(index);
      } else {
        return lineItemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Zkart.LineItem lineItems = 4;</code>
     */
    public Builder setLineItems(
        int index, protobuilder.LineItem value) {
      if (lineItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLineItemsIsMutable();
        lineItems_.set(index, value);
        onChanged();
      } else {
        lineItemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.LineItem lineItems = 4;</code>
     */
    public Builder setLineItems(
        int index, protobuilder.LineItem.Builder builderForValue) {
      if (lineItemsBuilder_ == null) {
        ensureLineItemsIsMutable();
        lineItems_.set(index, builderForValue.build());
        onChanged();
      } else {
        lineItemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.LineItem lineItems = 4;</code>
     */
    public Builder addLineItems(protobuilder.LineItem value) {
      if (lineItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLineItemsIsMutable();
        lineItems_.add(value);
        onChanged();
      } else {
        lineItemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.LineItem lineItems = 4;</code>
     */
    public Builder addLineItems(
        int index, protobuilder.LineItem value) {
      if (lineItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLineItemsIsMutable();
        lineItems_.add(index, value);
        onChanged();
      } else {
        lineItemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.LineItem lineItems = 4;</code>
     */
    public Builder addLineItems(
        protobuilder.LineItem.Builder builderForValue) {
      if (lineItemsBuilder_ == null) {
        ensureLineItemsIsMutable();
        lineItems_.add(builderForValue.build());
        onChanged();
      } else {
        lineItemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.LineItem lineItems = 4;</code>
     */
    public Builder addLineItems(
        int index, protobuilder.LineItem.Builder builderForValue) {
      if (lineItemsBuilder_ == null) {
        ensureLineItemsIsMutable();
        lineItems_.add(index, builderForValue.build());
        onChanged();
      } else {
        lineItemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.LineItem lineItems = 4;</code>
     */
    public Builder addAllLineItems(
        java.lang.Iterable<? extends protobuilder.LineItem> values) {
      if (lineItemsBuilder_ == null) {
        ensureLineItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, lineItems_);
        onChanged();
      } else {
        lineItemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.LineItem lineItems = 4;</code>
     */
    public Builder clearLineItems() {
      if (lineItemsBuilder_ == null) {
        lineItems_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        lineItemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.LineItem lineItems = 4;</code>
     */
    public Builder removeLineItems(int index) {
      if (lineItemsBuilder_ == null) {
        ensureLineItemsIsMutable();
        lineItems_.remove(index);
        onChanged();
      } else {
        lineItemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.LineItem lineItems = 4;</code>
     */
    public protobuilder.LineItem.Builder getLineItemsBuilder(
        int index) {
      return getLineItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Zkart.LineItem lineItems = 4;</code>
     */
    public protobuilder.LineItemOrBuilder getLineItemsOrBuilder(
        int index) {
      if (lineItemsBuilder_ == null) {
        return lineItems_.get(index);  } else {
        return lineItemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Zkart.LineItem lineItems = 4;</code>
     */
    public java.util.List<? extends protobuilder.LineItemOrBuilder> 
         getLineItemsOrBuilderList() {
      if (lineItemsBuilder_ != null) {
        return lineItemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(lineItems_);
      }
    }
    /**
     * <code>repeated .Zkart.LineItem lineItems = 4;</code>
     */
    public protobuilder.LineItem.Builder addLineItemsBuilder() {
      return getLineItemsFieldBuilder().addBuilder(
          protobuilder.LineItem.getDefaultInstance());
    }
    /**
     * <code>repeated .Zkart.LineItem lineItems = 4;</code>
     */
    public protobuilder.LineItem.Builder addLineItemsBuilder(
        int index) {
      return getLineItemsFieldBuilder().addBuilder(
          index, protobuilder.LineItem.getDefaultInstance());
    }
    /**
     * <code>repeated .Zkart.LineItem lineItems = 4;</code>
     */
    public java.util.List<protobuilder.LineItem.Builder> 
         getLineItemsBuilderList() {
      return getLineItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuilder.LineItem, protobuilder.LineItem.Builder, protobuilder.LineItemOrBuilder> 
        getLineItemsFieldBuilder() {
      if (lineItemsBuilder_ == null) {
        lineItemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protobuilder.LineItem, protobuilder.LineItem.Builder, protobuilder.LineItemOrBuilder>(
                lineItems_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        lineItems_ = null;
      }
      return lineItemsBuilder_;
    }

    private double subTotal_ ;
    /**
     * <code>required double subTotal = 5;</code>
     * @return Whether the subTotal field is set.
     */
    @java.lang.Override
    public boolean hasSubTotal() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required double subTotal = 5;</code>
     * @return The subTotal.
     */
    @java.lang.Override
    public double getSubTotal() {
      return subTotal_;
    }
    /**
     * <code>required double subTotal = 5;</code>
     * @param value The subTotal to set.
     * @return This builder for chaining.
     */
    public Builder setSubTotal(double value) {
      bitField0_ |= 0x00000010;
      subTotal_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required double subTotal = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSubTotal() {
      bitField0_ = (bitField0_ & ~0x00000010);
      subTotal_ = 0D;
      onChanged();
      return this;
    }

    private double discount_ ;
    /**
     * <code>optional double discount = 6;</code>
     * @return Whether the discount field is set.
     */
    @java.lang.Override
    public boolean hasDiscount() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional double discount = 6;</code>
     * @return The discount.
     */
    @java.lang.Override
    public double getDiscount() {
      return discount_;
    }
    /**
     * <code>optional double discount = 6;</code>
     * @param value The discount to set.
     * @return This builder for chaining.
     */
    public Builder setDiscount(double value) {
      bitField0_ |= 0x00000020;
      discount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional double discount = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDiscount() {
      bitField0_ = (bitField0_ & ~0x00000020);
      discount_ = 0D;
      onChanged();
      return this;
    }

    private double total_ ;
    /**
     * <code>required double total = 7;</code>
     * @return Whether the total field is set.
     */
    @java.lang.Override
    public boolean hasTotal() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>required double total = 7;</code>
     * @return The total.
     */
    @java.lang.Override
    public double getTotal() {
      return total_;
    }
    /**
     * <code>required double total = 7;</code>
     * @param value The total to set.
     * @return This builder for chaining.
     */
    public Builder setTotal(double value) {
      bitField0_ |= 0x00000040;
      total_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required double total = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotal() {
      bitField0_ = (bitField0_ & ~0x00000040);
      total_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Zkart.Invoice)
  }

  // @@protoc_insertion_point(class_scope:Zkart.Invoice)
  private static final protobuilder.Invoice DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuilder.Invoice();
  }

  public static protobuilder.Invoice getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Invoice>
      PARSER = new com.google.protobuf.AbstractParser<Invoice>() {
    @java.lang.Override
    public Invoice parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Invoice(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Invoice> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Invoice> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protobuilder.Invoice getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

