// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/Zkart.proto

package protobuilder;

public interface InvoiceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Zkart.Invoice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>required int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>required string date = 2;</code>
   * @return Whether the date field is set.
   */
  boolean hasDate();
  /**
   * <code>required string date = 2;</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <code>required string date = 2;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>required int64 customerID = 3;</code>
   * @return Whether the customerID field is set.
   */
  boolean hasCustomerID();
  /**
   * <code>required int64 customerID = 3;</code>
   * @return The customerID.
   */
  long getCustomerID();

  /**
   * <code>repeated .Zkart.LineItem lineItems = 4;</code>
   */
  java.util.List<protobuilder.LineItem> 
      getLineItemsList();
  /**
   * <code>repeated .Zkart.LineItem lineItems = 4;</code>
   */
  protobuilder.LineItem getLineItems(int index);
  /**
   * <code>repeated .Zkart.LineItem lineItems = 4;</code>
   */
  int getLineItemsCount();
  /**
   * <code>repeated .Zkart.LineItem lineItems = 4;</code>
   */
  java.util.List<? extends protobuilder.LineItemOrBuilder> 
      getLineItemsOrBuilderList();
  /**
   * <code>repeated .Zkart.LineItem lineItems = 4;</code>
   */
  protobuilder.LineItemOrBuilder getLineItemsOrBuilder(
      int index);

  /**
   * <code>required double subTotal = 5;</code>
   * @return Whether the subTotal field is set.
   */
  boolean hasSubTotal();
  /**
   * <code>required double subTotal = 5;</code>
   * @return The subTotal.
   */
  double getSubTotal();

  /**
   * <code>optional double discount = 6;</code>
   * @return Whether the discount field is set.
   */
  boolean hasDiscount();
  /**
   * <code>optional double discount = 6;</code>
   * @return The discount.
   */
  double getDiscount();

  /**
   * <code>required double total = 7;</code>
   * @return Whether the total field is set.
   */
  boolean hasTotal();
  /**
   * <code>required double total = 7;</code>
   * @return The total.
   */
  double getTotal();
}
