// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/Zkart.proto

package protobuilder;

/**
 * Protobuf type {@code Zkart.LineItem}
 */
public final class LineItem extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Zkart.LineItem)
    LineItemOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LineItem.newBuilder() to construct.
  private LineItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LineItem() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LineItem();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LineItem(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            id_ = input.readInt64();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            invoiceID_ = input.readInt64();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            productID_ = input.readInt64();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            quantity_ = input.readInt32();
            break;
          }
          case 41: {
            bitField0_ |= 0x00000010;
            itemRate_ = input.readDouble();
            break;
          }
          case 49: {
            bitField0_ |= 0x00000020;
            lineItemTotal_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuilder.ZkartProtos.internal_static_Zkart_LineItem_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuilder.ZkartProtos.internal_static_Zkart_LineItem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuilder.LineItem.class, protobuilder.LineItem.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>required int64 id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int INVOICEID_FIELD_NUMBER = 2;
  private long invoiceID_;
  /**
   * <code>required int64 invoiceID = 2;</code>
   * @return Whether the invoiceID field is set.
   */
  @java.lang.Override
  public boolean hasInvoiceID() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required int64 invoiceID = 2;</code>
   * @return The invoiceID.
   */
  @java.lang.Override
  public long getInvoiceID() {
    return invoiceID_;
  }

  public static final int PRODUCTID_FIELD_NUMBER = 3;
  private long productID_;
  /**
   * <code>required int64 productID = 3;</code>
   * @return Whether the productID field is set.
   */
  @java.lang.Override
  public boolean hasProductID() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required int64 productID = 3;</code>
   * @return The productID.
   */
  @java.lang.Override
  public long getProductID() {
    return productID_;
  }

  public static final int QUANTITY_FIELD_NUMBER = 4;
  private int quantity_;
  /**
   * <code>required int32 quantity = 4;</code>
   * @return Whether the quantity field is set.
   */
  @java.lang.Override
  public boolean hasQuantity() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>required int32 quantity = 4;</code>
   * @return The quantity.
   */
  @java.lang.Override
  public int getQuantity() {
    return quantity_;
  }

  public static final int ITEMRATE_FIELD_NUMBER = 5;
  private double itemRate_;
  /**
   * <code>required double itemRate = 5;</code>
   * @return Whether the itemRate field is set.
   */
  @java.lang.Override
  public boolean hasItemRate() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>required double itemRate = 5;</code>
   * @return The itemRate.
   */
  @java.lang.Override
  public double getItemRate() {
    return itemRate_;
  }

  public static final int LINEITEMTOTAL_FIELD_NUMBER = 6;
  private double lineItemTotal_;
  /**
   * <code>required double lineItemTotal = 6;</code>
   * @return Whether the lineItemTotal field is set.
   */
  @java.lang.Override
  public boolean hasLineItemTotal() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>required double lineItemTotal = 6;</code>
   * @return The lineItemTotal.
   */
  @java.lang.Override
  public double getLineItemTotal() {
    return lineItemTotal_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasInvoiceID()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasProductID()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasQuantity()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasItemRate()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasLineItemTotal()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt64(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(2, invoiceID_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt64(3, productID_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt32(4, quantity_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeDouble(5, itemRate_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeDouble(6, lineItemTotal_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, invoiceID_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, productID_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, quantity_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, itemRate_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, lineItemTotal_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuilder.LineItem)) {
      return super.equals(obj);
    }
    protobuilder.LineItem other = (protobuilder.LineItem) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (getId()
          != other.getId()) return false;
    }
    if (hasInvoiceID() != other.hasInvoiceID()) return false;
    if (hasInvoiceID()) {
      if (getInvoiceID()
          != other.getInvoiceID()) return false;
    }
    if (hasProductID() != other.hasProductID()) return false;
    if (hasProductID()) {
      if (getProductID()
          != other.getProductID()) return false;
    }
    if (hasQuantity() != other.hasQuantity()) return false;
    if (hasQuantity()) {
      if (getQuantity()
          != other.getQuantity()) return false;
    }
    if (hasItemRate() != other.hasItemRate()) return false;
    if (hasItemRate()) {
      if (java.lang.Double.doubleToLongBits(getItemRate())
          != java.lang.Double.doubleToLongBits(
              other.getItemRate())) return false;
    }
    if (hasLineItemTotal() != other.hasLineItemTotal()) return false;
    if (hasLineItemTotal()) {
      if (java.lang.Double.doubleToLongBits(getLineItemTotal())
          != java.lang.Double.doubleToLongBits(
              other.getLineItemTotal())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
    }
    if (hasInvoiceID()) {
      hash = (37 * hash) + INVOICEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getInvoiceID());
    }
    if (hasProductID()) {
      hash = (37 * hash) + PRODUCTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProductID());
    }
    if (hasQuantity()) {
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity();
    }
    if (hasItemRate()) {
      hash = (37 * hash) + ITEMRATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getItemRate()));
    }
    if (hasLineItemTotal()) {
      hash = (37 * hash) + LINEITEMTOTAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLineItemTotal()));
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuilder.LineItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuilder.LineItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuilder.LineItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuilder.LineItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuilder.LineItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuilder.LineItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuilder.LineItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuilder.LineItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuilder.LineItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuilder.LineItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuilder.LineItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuilder.LineItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuilder.LineItem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Zkart.LineItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Zkart.LineItem)
      protobuilder.LineItemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuilder.ZkartProtos.internal_static_Zkart_LineItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuilder.ZkartProtos.internal_static_Zkart_LineItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuilder.LineItem.class, protobuilder.LineItem.Builder.class);
    }

    // Construct using protobuilder.LineItem.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      invoiceID_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      productID_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      quantity_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      itemRate_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000010);
      lineItemTotal_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuilder.ZkartProtos.internal_static_Zkart_LineItem_descriptor;
    }

    @java.lang.Override
    public protobuilder.LineItem getDefaultInstanceForType() {
      return protobuilder.LineItem.getDefaultInstance();
    }

    @java.lang.Override
    public protobuilder.LineItem build() {
      protobuilder.LineItem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protobuilder.LineItem buildPartial() {
      protobuilder.LineItem result = new protobuilder.LineItem(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.invoiceID_ = invoiceID_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.productID_ = productID_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.quantity_ = quantity_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.itemRate_ = itemRate_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.lineItemTotal_ = lineItemTotal_;
        to_bitField0_ |= 0x00000020;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuilder.LineItem) {
        return mergeFrom((protobuilder.LineItem)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuilder.LineItem other) {
      if (other == protobuilder.LineItem.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasInvoiceID()) {
        setInvoiceID(other.getInvoiceID());
      }
      if (other.hasProductID()) {
        setProductID(other.getProductID());
      }
      if (other.hasQuantity()) {
        setQuantity(other.getQuantity());
      }
      if (other.hasItemRate()) {
        setItemRate(other.getItemRate());
      }
      if (other.hasLineItemTotal()) {
        setLineItemTotal(other.getLineItemTotal());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasId()) {
        return false;
      }
      if (!hasInvoiceID()) {
        return false;
      }
      if (!hasProductID()) {
        return false;
      }
      if (!hasQuantity()) {
        return false;
      }
      if (!hasItemRate()) {
        return false;
      }
      if (!hasLineItemTotal()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuilder.LineItem parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuilder.LineItem) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>required int64 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>required int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private long invoiceID_ ;
    /**
     * <code>required int64 invoiceID = 2;</code>
     * @return Whether the invoiceID field is set.
     */
    @java.lang.Override
    public boolean hasInvoiceID() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int64 invoiceID = 2;</code>
     * @return The invoiceID.
     */
    @java.lang.Override
    public long getInvoiceID() {
      return invoiceID_;
    }
    /**
     * <code>required int64 invoiceID = 2;</code>
     * @param value The invoiceID to set.
     * @return This builder for chaining.
     */
    public Builder setInvoiceID(long value) {
      bitField0_ |= 0x00000002;
      invoiceID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 invoiceID = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearInvoiceID() {
      bitField0_ = (bitField0_ & ~0x00000002);
      invoiceID_ = 0L;
      onChanged();
      return this;
    }

    private long productID_ ;
    /**
     * <code>required int64 productID = 3;</code>
     * @return Whether the productID field is set.
     */
    @java.lang.Override
    public boolean hasProductID() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int64 productID = 3;</code>
     * @return The productID.
     */
    @java.lang.Override
    public long getProductID() {
      return productID_;
    }
    /**
     * <code>required int64 productID = 3;</code>
     * @param value The productID to set.
     * @return This builder for chaining.
     */
    public Builder setProductID(long value) {
      bitField0_ |= 0x00000004;
      productID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 productID = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductID() {
      bitField0_ = (bitField0_ & ~0x00000004);
      productID_ = 0L;
      onChanged();
      return this;
    }

    private int quantity_ ;
    /**
     * <code>required int32 quantity = 4;</code>
     * @return Whether the quantity field is set.
     */
    @java.lang.Override
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required int32 quantity = 4;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public int getQuantity() {
      return quantity_;
    }
    /**
     * <code>required int32 quantity = 4;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(int value) {
      bitField0_ |= 0x00000008;
      quantity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 quantity = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      bitField0_ = (bitField0_ & ~0x00000008);
      quantity_ = 0;
      onChanged();
      return this;
    }

    private double itemRate_ ;
    /**
     * <code>required double itemRate = 5;</code>
     * @return Whether the itemRate field is set.
     */
    @java.lang.Override
    public boolean hasItemRate() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required double itemRate = 5;</code>
     * @return The itemRate.
     */
    @java.lang.Override
    public double getItemRate() {
      return itemRate_;
    }
    /**
     * <code>required double itemRate = 5;</code>
     * @param value The itemRate to set.
     * @return This builder for chaining.
     */
    public Builder setItemRate(double value) {
      bitField0_ |= 0x00000010;
      itemRate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required double itemRate = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearItemRate() {
      bitField0_ = (bitField0_ & ~0x00000010);
      itemRate_ = 0D;
      onChanged();
      return this;
    }

    private double lineItemTotal_ ;
    /**
     * <code>required double lineItemTotal = 6;</code>
     * @return Whether the lineItemTotal field is set.
     */
    @java.lang.Override
    public boolean hasLineItemTotal() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required double lineItemTotal = 6;</code>
     * @return The lineItemTotal.
     */
    @java.lang.Override
    public double getLineItemTotal() {
      return lineItemTotal_;
    }
    /**
     * <code>required double lineItemTotal = 6;</code>
     * @param value The lineItemTotal to set.
     * @return This builder for chaining.
     */
    public Builder setLineItemTotal(double value) {
      bitField0_ |= 0x00000020;
      lineItemTotal_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required double lineItemTotal = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLineItemTotal() {
      bitField0_ = (bitField0_ & ~0x00000020);
      lineItemTotal_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Zkart.LineItem)
  }

  // @@protoc_insertion_point(class_scope:Zkart.LineItem)
  private static final protobuilder.LineItem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuilder.LineItem();
  }

  public static protobuilder.LineItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<LineItem>
      PARSER = new com.google.protobuf.AbstractParser<LineItem>() {
    @java.lang.Override
    public LineItem parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LineItem(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LineItem> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LineItem> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protobuilder.LineItem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

