// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/Zkart.proto

package protobuilder;

public interface LineItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Zkart.LineItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>required int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>required int64 invoiceID = 2;</code>
   * @return Whether the invoiceID field is set.
   */
  boolean hasInvoiceID();
  /**
   * <code>required int64 invoiceID = 2;</code>
   * @return The invoiceID.
   */
  long getInvoiceID();

  /**
   * <code>required int64 productID = 3;</code>
   * @return Whether the productID field is set.
   */
  boolean hasProductID();
  /**
   * <code>required int64 productID = 3;</code>
   * @return The productID.
   */
  long getProductID();

  /**
   * <code>required int32 quantity = 4;</code>
   * @return Whether the quantity field is set.
   */
  boolean hasQuantity();
  /**
   * <code>required int32 quantity = 4;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <code>required double itemRate = 5;</code>
   * @return Whether the itemRate field is set.
   */
  boolean hasItemRate();
  /**
   * <code>required double itemRate = 5;</code>
   * @return The itemRate.
   */
  double getItemRate();

  /**
   * <code>required double lineItemTotal = 6;</code>
   * @return Whether the lineItemTotal field is set.
   */
  boolean hasLineItemTotal();
  /**
   * <code>required double lineItemTotal = 6;</code>
   * @return The lineItemTotal.
   */
  double getLineItemTotal();
}
