// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/Zkart.proto

package protobuilder;

/**
 * Protobuf type {@code Zkart.Orders}
 */
public final class Orders extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Zkart.Orders)
    OrdersOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Orders.newBuilder() to construct.
  private Orders(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Orders() {
    invoices_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Orders();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Orders(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              invoices_ = new java.util.ArrayList<protobuilder.Invoice>();
              mutable_bitField0_ |= 0x00000001;
            }
            invoices_.add(
                input.readMessage(protobuilder.Invoice.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        invoices_ = java.util.Collections.unmodifiableList(invoices_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuilder.ZkartProtos.internal_static_Zkart_Orders_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuilder.ZkartProtos.internal_static_Zkart_Orders_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuilder.Orders.class, protobuilder.Orders.Builder.class);
  }

  public static final int INVOICES_FIELD_NUMBER = 1;
  private java.util.List<protobuilder.Invoice> invoices_;
  /**
   * <code>repeated .Zkart.Invoice invoices = 1;</code>
   */
  @java.lang.Override
  public java.util.List<protobuilder.Invoice> getInvoicesList() {
    return invoices_;
  }
  /**
   * <code>repeated .Zkart.Invoice invoices = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends protobuilder.InvoiceOrBuilder> 
      getInvoicesOrBuilderList() {
    return invoices_;
  }
  /**
   * <code>repeated .Zkart.Invoice invoices = 1;</code>
   */
  @java.lang.Override
  public int getInvoicesCount() {
    return invoices_.size();
  }
  /**
   * <code>repeated .Zkart.Invoice invoices = 1;</code>
   */
  @java.lang.Override
  public protobuilder.Invoice getInvoices(int index) {
    return invoices_.get(index);
  }
  /**
   * <code>repeated .Zkart.Invoice invoices = 1;</code>
   */
  @java.lang.Override
  public protobuilder.InvoiceOrBuilder getInvoicesOrBuilder(
      int index) {
    return invoices_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getInvoicesCount(); i++) {
      if (!getInvoices(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < invoices_.size(); i++) {
      output.writeMessage(1, invoices_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < invoices_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, invoices_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuilder.Orders)) {
      return super.equals(obj);
    }
    protobuilder.Orders other = (protobuilder.Orders) obj;

    if (!getInvoicesList()
        .equals(other.getInvoicesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getInvoicesCount() > 0) {
      hash = (37 * hash) + INVOICES_FIELD_NUMBER;
      hash = (53 * hash) + getInvoicesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuilder.Orders parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuilder.Orders parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuilder.Orders parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuilder.Orders parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuilder.Orders parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuilder.Orders parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuilder.Orders parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuilder.Orders parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuilder.Orders parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuilder.Orders parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuilder.Orders parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuilder.Orders parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuilder.Orders prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Zkart.Orders}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Zkart.Orders)
      protobuilder.OrdersOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuilder.ZkartProtos.internal_static_Zkart_Orders_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuilder.ZkartProtos.internal_static_Zkart_Orders_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuilder.Orders.class, protobuilder.Orders.Builder.class);
    }

    // Construct using protobuilder.Orders.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getInvoicesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (invoicesBuilder_ == null) {
        invoices_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        invoicesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuilder.ZkartProtos.internal_static_Zkart_Orders_descriptor;
    }

    @java.lang.Override
    public protobuilder.Orders getDefaultInstanceForType() {
      return protobuilder.Orders.getDefaultInstance();
    }

    @java.lang.Override
    public protobuilder.Orders build() {
      protobuilder.Orders result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protobuilder.Orders buildPartial() {
      protobuilder.Orders result = new protobuilder.Orders(this);
      int from_bitField0_ = bitField0_;
      if (invoicesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          invoices_ = java.util.Collections.unmodifiableList(invoices_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.invoices_ = invoices_;
      } else {
        result.invoices_ = invoicesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuilder.Orders) {
        return mergeFrom((protobuilder.Orders)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuilder.Orders other) {
      if (other == protobuilder.Orders.getDefaultInstance()) return this;
      if (invoicesBuilder_ == null) {
        if (!other.invoices_.isEmpty()) {
          if (invoices_.isEmpty()) {
            invoices_ = other.invoices_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInvoicesIsMutable();
            invoices_.addAll(other.invoices_);
          }
          onChanged();
        }
      } else {
        if (!other.invoices_.isEmpty()) {
          if (invoicesBuilder_.isEmpty()) {
            invoicesBuilder_.dispose();
            invoicesBuilder_ = null;
            invoices_ = other.invoices_;
            bitField0_ = (bitField0_ & ~0x00000001);
            invoicesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInvoicesFieldBuilder() : null;
          } else {
            invoicesBuilder_.addAllMessages(other.invoices_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      for (int i = 0; i < getInvoicesCount(); i++) {
        if (!getInvoices(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuilder.Orders parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuilder.Orders) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<protobuilder.Invoice> invoices_ =
      java.util.Collections.emptyList();
    private void ensureInvoicesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        invoices_ = new java.util.ArrayList<protobuilder.Invoice>(invoices_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuilder.Invoice, protobuilder.Invoice.Builder, protobuilder.InvoiceOrBuilder> invoicesBuilder_;

    /**
     * <code>repeated .Zkart.Invoice invoices = 1;</code>
     */
    public java.util.List<protobuilder.Invoice> getInvoicesList() {
      if (invoicesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(invoices_);
      } else {
        return invoicesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Zkart.Invoice invoices = 1;</code>
     */
    public int getInvoicesCount() {
      if (invoicesBuilder_ == null) {
        return invoices_.size();
      } else {
        return invoicesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Zkart.Invoice invoices = 1;</code>
     */
    public protobuilder.Invoice getInvoices(int index) {
      if (invoicesBuilder_ == null) {
        return invoices_.get(index);
      } else {
        return invoicesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Zkart.Invoice invoices = 1;</code>
     */
    public Builder setInvoices(
        int index, protobuilder.Invoice value) {
      if (invoicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvoicesIsMutable();
        invoices_.set(index, value);
        onChanged();
      } else {
        invoicesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Invoice invoices = 1;</code>
     */
    public Builder setInvoices(
        int index, protobuilder.Invoice.Builder builderForValue) {
      if (invoicesBuilder_ == null) {
        ensureInvoicesIsMutable();
        invoices_.set(index, builderForValue.build());
        onChanged();
      } else {
        invoicesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Invoice invoices = 1;</code>
     */
    public Builder addInvoices(protobuilder.Invoice value) {
      if (invoicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvoicesIsMutable();
        invoices_.add(value);
        onChanged();
      } else {
        invoicesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Invoice invoices = 1;</code>
     */
    public Builder addInvoices(
        int index, protobuilder.Invoice value) {
      if (invoicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvoicesIsMutable();
        invoices_.add(index, value);
        onChanged();
      } else {
        invoicesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Invoice invoices = 1;</code>
     */
    public Builder addInvoices(
        protobuilder.Invoice.Builder builderForValue) {
      if (invoicesBuilder_ == null) {
        ensureInvoicesIsMutable();
        invoices_.add(builderForValue.build());
        onChanged();
      } else {
        invoicesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Invoice invoices = 1;</code>
     */
    public Builder addInvoices(
        int index, protobuilder.Invoice.Builder builderForValue) {
      if (invoicesBuilder_ == null) {
        ensureInvoicesIsMutable();
        invoices_.add(index, builderForValue.build());
        onChanged();
      } else {
        invoicesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Invoice invoices = 1;</code>
     */
    public Builder addAllInvoices(
        java.lang.Iterable<? extends protobuilder.Invoice> values) {
      if (invoicesBuilder_ == null) {
        ensureInvoicesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, invoices_);
        onChanged();
      } else {
        invoicesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Invoice invoices = 1;</code>
     */
    public Builder clearInvoices() {
      if (invoicesBuilder_ == null) {
        invoices_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        invoicesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Invoice invoices = 1;</code>
     */
    public Builder removeInvoices(int index) {
      if (invoicesBuilder_ == null) {
        ensureInvoicesIsMutable();
        invoices_.remove(index);
        onChanged();
      } else {
        invoicesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Zkart.Invoice invoices = 1;</code>
     */
    public protobuilder.Invoice.Builder getInvoicesBuilder(
        int index) {
      return getInvoicesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Zkart.Invoice invoices = 1;</code>
     */
    public protobuilder.InvoiceOrBuilder getInvoicesOrBuilder(
        int index) {
      if (invoicesBuilder_ == null) {
        return invoices_.get(index);  } else {
        return invoicesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Zkart.Invoice invoices = 1;</code>
     */
    public java.util.List<? extends protobuilder.InvoiceOrBuilder> 
         getInvoicesOrBuilderList() {
      if (invoicesBuilder_ != null) {
        return invoicesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(invoices_);
      }
    }
    /**
     * <code>repeated .Zkart.Invoice invoices = 1;</code>
     */
    public protobuilder.Invoice.Builder addInvoicesBuilder() {
      return getInvoicesFieldBuilder().addBuilder(
          protobuilder.Invoice.getDefaultInstance());
    }
    /**
     * <code>repeated .Zkart.Invoice invoices = 1;</code>
     */
    public protobuilder.Invoice.Builder addInvoicesBuilder(
        int index) {
      return getInvoicesFieldBuilder().addBuilder(
          index, protobuilder.Invoice.getDefaultInstance());
    }
    /**
     * <code>repeated .Zkart.Invoice invoices = 1;</code>
     */
    public java.util.List<protobuilder.Invoice.Builder> 
         getInvoicesBuilderList() {
      return getInvoicesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuilder.Invoice, protobuilder.Invoice.Builder, protobuilder.InvoiceOrBuilder> 
        getInvoicesFieldBuilder() {
      if (invoicesBuilder_ == null) {
        invoicesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protobuilder.Invoice, protobuilder.Invoice.Builder, protobuilder.InvoiceOrBuilder>(
                invoices_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        invoices_ = null;
      }
      return invoicesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Zkart.Orders)
  }

  // @@protoc_insertion_point(class_scope:Zkart.Orders)
  private static final protobuilder.Orders DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuilder.Orders();
  }

  public static protobuilder.Orders getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Orders>
      PARSER = new com.google.protobuf.AbstractParser<Orders>() {
    @java.lang.Override
    public Orders parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Orders(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Orders> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Orders> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protobuilder.Orders getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

