// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/Zkart.proto

package protobuilder;

public interface OrdersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Zkart.Orders)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Zkart.Invoice invoices = 1;</code>
   */
  java.util.List<protobuilder.Invoice> 
      getInvoicesList();
  /**
   * <code>repeated .Zkart.Invoice invoices = 1;</code>
   */
  protobuilder.Invoice getInvoices(int index);
  /**
   * <code>repeated .Zkart.Invoice invoices = 1;</code>
   */
  int getInvoicesCount();
  /**
   * <code>repeated .Zkart.Invoice invoices = 1;</code>
   */
  java.util.List<? extends protobuilder.InvoiceOrBuilder> 
      getInvoicesOrBuilderList();
  /**
   * <code>repeated .Zkart.Invoice invoices = 1;</code>
   */
  protobuilder.InvoiceOrBuilder getInvoicesOrBuilder(
      int index);
}
