// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/Zkart.proto

package protobuilder;

public interface ProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Zkart.Product)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>required int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>required string category = 2;</code>
   * @return Whether the category field is set.
   */
  boolean hasCategory();
  /**
   * <code>required string category = 2;</code>
   * @return The category.
   */
  java.lang.String getCategory();
  /**
   * <code>required string category = 2;</code>
   * @return The bytes for category.
   */
  com.google.protobuf.ByteString
      getCategoryBytes();

  /**
   * <code>required string brand = 3;</code>
   * @return Whether the brand field is set.
   */
  boolean hasBrand();
  /**
   * <code>required string brand = 3;</code>
   * @return The brand.
   */
  java.lang.String getBrand();
  /**
   * <code>required string brand = 3;</code>
   * @return The bytes for brand.
   */
  com.google.protobuf.ByteString
      getBrandBytes();

  /**
   * <code>required string model = 4;</code>
   * @return Whether the model field is set.
   */
  boolean hasModel();
  /**
   * <code>required string model = 4;</code>
   * @return The model.
   */
  java.lang.String getModel();
  /**
   * <code>required string model = 4;</code>
   * @return The bytes for model.
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>required int32 stock = 5;</code>
   * @return Whether the stock field is set.
   */
  boolean hasStock();
  /**
   * <code>required int32 stock = 5;</code>
   * @return The stock.
   */
  int getStock();

  /**
   * <code>required double price = 6;</code>
   * @return Whether the price field is set.
   */
  boolean hasPrice();
  /**
   * <code>required double price = 6;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <code>optional double discountPrice = 7;</code>
   * @return Whether the discountPrice field is set.
   */
  boolean hasDiscountPrice();
  /**
   * <code>optional double discountPrice = 7;</code>
   * @return The discountPrice.
   */
  double getDiscountPrice();
}
