// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/Zkart.proto

package protobuilder;

public final class ZkartProtos {
  private ZkartProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Zkart_Product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Zkart_Product_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Zkart_LineItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Zkart_LineItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Zkart_Invoice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Zkart_Invoice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Zkart_Deal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Zkart_Deal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Zkart_CartItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Zkart_CartItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Zkart_Customer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Zkart_Customer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Zkart_Admin_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Zkart_Admin_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Zkart_AdminsDB_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Zkart_AdminsDB_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Zkart_CustomersDB_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Zkart_CustomersDB_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Zkart_InventoryDB_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Zkart_InventoryDB_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Zkart_DealsDB_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Zkart_DealsDB_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Zkart_Orders_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Zkart_Orders_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024compiler/Zkart.proto\022\005Zkart\"z\n\007Product" +
      "\022\n\n\002id\030\001 \002(\003\022\020\n\010category\030\002 \002(\t\022\r\n\005brand\030" +
      "\003 \002(\t\022\r\n\005model\030\004 \002(\t\022\r\n\005stock\030\005 \002(\005\022\r\n\005p" +
      "rice\030\006 \002(\001\022\025\n\rdiscountPrice\030\007 \001(\001\"w\n\010Lin" +
      "eItem\022\n\n\002id\030\001 \002(\003\022\021\n\tinvoiceID\030\002 \002(\003\022\021\n\t" +
      "productID\030\003 \002(\003\022\020\n\010quantity\030\004 \002(\005\022\020\n\010ite" +
      "mRate\030\005 \002(\001\022\025\n\rlineItemTotal\030\006 \002(\001\"\216\001\n\007I" +
      "nvoice\022\n\n\002id\030\001 \002(\003\022\014\n\004date\030\002 \002(\t\022\022\n\ncust" +
      "omerID\030\003 \002(\003\022\"\n\tlineItems\030\004 \003(\0132\017.Zkart." +
      "LineItem\022\020\n\010subTotal\030\005 \002(\001\022\020\n\010discount\030\006" +
      " \001(\001\022\r\n\005total\030\007 \002(\001\"\243\001\n\004Deal\022\n\n\002id\030\001 \002(\003" +
      "\022\016\n\006status\030\002 \001(\t\022\020\n\010dealName\030\003 \002(\t\022\024\n\014di" +
      "scountCode\030\004 \002(\t\022\027\n\017discountPercent\030\005 \002(" +
      "\001\022\036\n\026ordersAfterDealExpires\030\006 \002(\005\022\036\n\026las" +
      "tValidInvoiceNumber\030\007 \001(\005\"x\n\010CartItem\022\013\n" +
      "\003sNo\030\001 \002(\005\022\022\n\ncustomerID\030\002 \002(\003\022\021\n\tproduc" +
      "tID\030\003 \002(\003\022\020\n\010quantity\030\004 \002(\005\022\023\n\013productRa" +
      "te\030\005 \002(\001\022\021\n\tlineTotal\030\006 \002(\001\"\300\001\n\010Customer" +
      "\022\n\n\002id\030\001 \002(\003\022\014\n\004name\030\002 \002(\t\022\r\n\005email\030\003 \002(" +
      "\t\022\020\n\010password\030\004 \002(\t\022\023\n\013phoneNumber\030\005 \001(\003" +
      "\022\032\n\005deals\030\006 \003(\0132\013.Zkart.Deal\022\"\n\tcartItem" +
      "s\030\007 \003(\0132\017.Zkart.CartItem\022$\n\014orderHistory" +
      "\030\010 \003(\0132\016.Zkart.Invoice\"W\n\005Admin\022\n\n\002id\030\001 " +
      "\002(\003\022\014\n\004name\030\002 \002(\t\022\r\n\005email\030\003 \002(\t\022\020\n\010pass" +
      "word\030\004 \002(\t\022\023\n\013phoneNumber\030\005 \001(\003\"(\n\010Admin" +
      "sDB\022\034\n\006admins\030\001 \003(\0132\014.Zkart.Admin\"1\n\013Cus" +
      "tomersDB\022\"\n\tcustomers\030\001 \003(\0132\017.Zkart.Cust" +
      "omer\"/\n\013InventoryDB\022 \n\010products\030\001 \003(\0132\016." +
      "Zkart.Product\"%\n\007DealsDB\022\032\n\005deals\030\001 \003(\0132" +
      "\013.Zkart.Deal\"*\n\006Orders\022 \n\010invoices\030\001 \003(\013" +
      "2\016.Zkart.InvoiceB\035\n\014protobuilderB\013ZkartP" +
      "rotosP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Zkart_Product_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Zkart_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Zkart_Product_descriptor,
        new java.lang.String[] { "Id", "Category", "Brand", "Model", "Stock", "Price", "DiscountPrice", });
    internal_static_Zkart_LineItem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Zkart_LineItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Zkart_LineItem_descriptor,
        new java.lang.String[] { "Id", "InvoiceID", "ProductID", "Quantity", "ItemRate", "LineItemTotal", });
    internal_static_Zkart_Invoice_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Zkart_Invoice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Zkart_Invoice_descriptor,
        new java.lang.String[] { "Id", "Date", "CustomerID", "LineItems", "SubTotal", "Discount", "Total", });
    internal_static_Zkart_Deal_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Zkart_Deal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Zkart_Deal_descriptor,
        new java.lang.String[] { "Id", "Status", "DealName", "DiscountCode", "DiscountPercent", "OrdersAfterDealExpires", "LastValidInvoiceNumber", });
    internal_static_Zkart_CartItem_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Zkart_CartItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Zkart_CartItem_descriptor,
        new java.lang.String[] { "SNo", "CustomerID", "ProductID", "Quantity", "ProductRate", "LineTotal", });
    internal_static_Zkart_Customer_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Zkart_Customer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Zkart_Customer_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", "Password", "PhoneNumber", "Deals", "CartItems", "OrderHistory", });
    internal_static_Zkart_Admin_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Zkart_Admin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Zkart_Admin_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", "Password", "PhoneNumber", });
    internal_static_Zkart_AdminsDB_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Zkart_AdminsDB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Zkart_AdminsDB_descriptor,
        new java.lang.String[] { "Admins", });
    internal_static_Zkart_CustomersDB_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Zkart_CustomersDB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Zkart_CustomersDB_descriptor,
        new java.lang.String[] { "Customers", });
    internal_static_Zkart_InventoryDB_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_Zkart_InventoryDB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Zkart_InventoryDB_descriptor,
        new java.lang.String[] { "Products", });
    internal_static_Zkart_DealsDB_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_Zkart_DealsDB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Zkart_DealsDB_descriptor,
        new java.lang.String[] { "Deals", });
    internal_static_Zkart_Orders_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_Zkart_Orders_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Zkart_Orders_descriptor,
        new java.lang.String[] { "Invoices", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
